### ISSUE TITLE
Cannot build against Qt5 if Qt6 is installed

### ISSUE THREAD

**Issue by klemensn** [open-eid/DigiDoc4-Client#1097]
#991 introduced
https://github.com/open-eid/DigiDoc4-Client/blob/0b158fcfc2ca8ea04a0dd07a711073217e19e68d/CMakeLists.txt#L17-L18
which effectively prevents using Qt5 if Qt6 is installed.

Usually `-D CMAKE_DISABLE_FIND_PACKAGE_<PackageName>=ON` can be used to hide installed packages,
but `REQUIRED` prevents this.

Even without `REQUIRED`, due to the use of `NAMES` one had to pass
`-D CMAKE_DISABLE_FIND_PACKAGE_QT=ON` instead of
`-D CMAKE_DISABLE_FIND_PACKAGE_Qt6=ON` to neuter
https://github.com/open-eid/DigiDoc4-Client/blob/0b158fcfc2ca8ea04a0dd07a711073217e19e68d/CMakeLists.txt#L17
which in turn would cause `QT_VERSION_MAJOR` to be undefined and thus break
https://github.com/open-eid/DigiDoc4-Client/blob/0b158fcfc2ca8ea04a0dd07a711073217e19e68d/CMakeLists.txt#L18

Passing `-D CMAKE_DISABLE_FIND_PACKAGE_Qt6=ON` would equally break line 18, as can be seen here:
```
[...]
CMake Error at CMakeLists.txt:18 (find_package):
  find_package for module Qt6 called with REQUIRED, but
  CMAKE_DISABLE_FIND_PACKAGE_Qt6 is enabled.  A REQUIRED package cannot be
  disabled.
[...]
CMake Error at common/CMakeLists.txt:14 (qt_add_translation):
  Unknown CMake command "qt_add_translation".
[...]
-- Configuring incomplete, errors occurred!
```

So to buid against Qt5 one must either remove Qt6 from their system or patch line 17, e.g.
```
-find_package(QT NAMES Qt6 Qt5 COMPONENTS Core REQUIRED)
-find_package(QT NAMES Qt5 COMPONENTS Core REQUIRED)
```

One way to fix this is to introduce a CMake option like so:
```
set(DEFAULT_QT_VER 6)
option(QT_VERSION "Qt version to use (default: ${DEFAULT_QT_VER})" ${DEFAULT_QT_VER})
...
```

I have not opened a PR for this approach yet as there may be other ways.
Qt5 support is probably not going away soon, so it should keep working regardless of whether Qt6 is installed or not.

**Comment by metsma** [comment]
Can you test #1082

**Comment by klemensn** [comment]
> Can you test #1082

This PR contains no Qt related CMake changes, so it won't fix the Qt5 issue described here.

**Comment by metsma** [comment]
This is how Qt suggests to support QT 5 and 6 
https://doc.qt.io/qt-6/cmake-qt5-and-qt6-compatibility.html#supporting-older-qt-5-versions

**Comment by metsma** [comment]
Currently yes. Ubuntu 18.04  (Qt 5.9) is still supported target.
Windows moves now to Qt 6.3.

**Comment by klemensn** [comment]
> Currently yes. Ubuntu 18.04 (Qt 5.9) is still supported target. Windows moves now to Qt 6.3.

It still seems off to effectively force Qt6 usage if both Qt6 and Qt5 are installed, but since Qt6 works (for me on OpenBSD) I'll just stick to that and refrain from changing the CMake detection logic.

Maybe the versionless approach can be adapted once support for the last Qt<5.14 platform (Ubuntu 18.04) has been dropped?

**Comment by metsma** [comment]
> > Currently yes. Ubuntu 18.04 (Qt 5.9) is still supported target. Windows moves now to Qt 6.3.
> 
> It still seems off to effectively force Qt6 usage if both Qt6 and Qt5 are installed, but since Qt6 works (for me on OpenBSD) I'll just stick to that and refrain from changing the CMake detection logic.
> 
> Maybe the versionless approach can be adapted once support for the last Qt<5.14 platform (Ubuntu 18.04) has been dropped?

I am also looking forward for this day. Ubuntu 18.04 LTS has standard support until April 2023.
