### ISSUE TITLE
Can't install 'opensc' package on Ubuntu 22.04

### ISSUE THREAD

**Issue by plagov** [open-eid/DigiDoc4-Client#1115]
I have a fresh and clean installation of Ubuntu 22.04. I downloaded the installation script and run the script. It fails to install the DigiDoc4 because the `opensc` package could not be installed. Full output:
```shell
ubuntu@ubuntu:~/Downloads$ sh install-open-eid.sh 
Adding RIA repository to APT sources list (/etc/apt/sources.list.d/ria-repository.list)
deb https://installer.id.ee/media/ubuntu/ jammy main
Adding key to trusted key set (apt-key add)
0xC6C83D68 'RIA Software Signing Key <signing@ria.ee>'
Installing software (apt-get update && apt-get install open-eid)
Ign:1 cdrom://Ubuntu 22.04.1 LTS _Jammy Jellyfish_ - Release amd64 (20220809.1) jammy InRelease
Hit:2 cdrom://Ubuntu 22.04.1 LTS _Jammy Jellyfish_ - Release amd64 (20220809.1) jammy Release
Hit:3 https://installer.id.ee/media/ubuntu jammy InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease                                    
Hit:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease                            
Hit:7 http://security.ubuntu.com/ubuntu jammy-security InRelease             
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package opensc is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'opensc' has no installation candidate
```

Running the `sudo apt-get install opensc` also doesn't help and package cannot be installed:

```shell
ubuntu@ubuntu:~/Downloads$ sudo apt-get install opensc
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package opensc is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'opensc' has no installation candidate
```

How can I install the `opensc` package to be able to install the DigiDoc4 client?

**Comment by MartinEesmaa** [comment]
Tere, @plagov.

Can you replace the word `apt-get` by `apt` to work to install opensc? 

If not, try manually download Ubuntu package of opensc:
https://packages.ubuntu.com/jammy/amd64/opensc/download

Once, you downloaded the package, run code:
```
sudo dpkg --install opensc_0.22.0-1ubuntu2_amd64.deb
```

If didn't work everything, you need to build opensc on your system:
https://github.com/OpenSC/OpenSC/wiki/Compiling-and-Installing-on-Unix-flavors

Any questions or issues, please let me know.

Regards
- Martin Eesmaa

**Comment by plagov** [comment]
Hi, @MartinEesmaa,

I tried again with `apt` and then manually installed the `deb` package but couldn't make it work.
I gave up eventually.

**Comment by kristelmerilain** [comment]
Thank you for the feedback!
Unfortunately, we were not able to reproduce this issue in fresh and clean installation of Ubuntu 22.04.
Maybe this will help:
`apt clean && apt update && apt install opensc`

**Comment by plagov** [comment]
Thank you @kristelmerilain 
I was trying the "Live" version of Ubuntu 22.04. I.e., trying it live from the USB stick without installing it first. Maybe that was the case. Unlikely, but who knows?

Ok, I will leave it as is and will try again if/when I install the Ubuntu permanently on my machine.
