### ISSUE TITLE
(32 bit x86) error: narrowing conversion of '-2146435062' from 'LONG' {aka 'long int'} to 'long unsigned int'

### ISSUE THREAD

**Issue by Germano0** [open-eid/DigiDoc4-Client#1119]
Hello, digidoc 4.2.12 Linux build is failing on x86 32 bit only, with following error
```
/builddir/build/BUILD/qdigidoc4-4.2.12/common/QPCSC.cpp: In member function 'bool QPCSCReader::updateState(quint32)':
/builddir/build/BUILD/qdigidoc4-4.2.12/common/QPCSC.cpp:519:14: error: narrowing conversion of '-2146435062' from 'LONG' {aka 'long int'} to 'long unsigned int' [-Wnarrowing]
  519 |         case SCARD_E_TIMEOUT: return msec == 0;
      |              ^~~~~~~~~~~~~~~
gmake[2]: *** [common/CMakeFiles/qdigidoccommon.dir/build.make:159: common/CMakeFiles/qdigidoccommon.dir/QPCSC.cpp.o] Error 1
```

full log https://kojipkgs.fedoraproject.org//work/tasks/2963/91952963/build.log
build logs https://koji.fedoraproject.org/koji/taskinfo?taskID=91952963

(instead) successfull build on x86 64bit https://koji.fedoraproject.org/koji/taskinfo?taskID=91952964

**Comment by metsma** [comment]
Maybe this is related to https://github.com/open-eid/qt-common/pull/124

**Comment by kristelmerilain** [comment]
Closing due inactivity, reopen if needed.

**Comment by Germano0** [comment]
yes the patch fixed the problem.
Best regards
