### ISSUE TITLE
show what certificates are allowed

### ISSUE THREAD

**Issue by weiwu-zhang** [open-eid/DigiDoc4-Client#1120]
I know this may be the wrong place to ask, kindly advise me.

When encrypting a document, there is the option of encrypting a file using a **CERTIFICATE FROM FILE**: 

![image](https://user-images.githubusercontent.com/548435/190454838-9a2cb81c-aa31-4807-8db8-85930a8724a6.png)

It is not clear what certificates are accepted. Of course, it would be x.509, but what key, and what length? Is there a requirement that the certificate must be issued from eesti (and not self-signed)? Would be great if there is an openssl example to generate a certificate (from a known compatible key format).

I had a quick glance, the client checks for `ExtendedKeyUsage`, at least, but not sure if it is all what is required.
https://github.com/open-eid/DigiDoc4-Client/blob/df35a89b0701b9fc6b0759eb2d93f6bc0974439a/client/dialogs/AddRecipients.cpp#L175-L176

In anyway, if none-eesti-signed certificates are allowed, the user interface should allow a question mark button to explain what formats are allowed.

**Comment by kristelmerilain** [comment]
Certificates don't need to be issued by Estonia. Only restriction on encryption is that keyUsage extension must contain KeyEncipherment or KeyAgreement.
