### ISSUE TITLE
Error "Signature is unknown" for signature containers containing an invalid OCSP response

### ISSUE THREAD

**Issue by user8547** [open-eid/DigiDoc4-Client#1131]
When a signature container contains an OCSP response that contains validity status of a different certificate serial number than the signatory's certificate included in the signature, DigiDoc4 client shows an error "Signature is unknown" and technical information section wrongly reports that certificate status is unknown (while the status is "Good"). However, it should show "Signature is not valid" with an appropriate description in the technical information section (e.g., "OCSP response does not match signatory's certificate").

![Screenshot from 2022-10-18 17-26-46](https://user-images.githubusercontent.com/6662385/196458701-899390cc-477e-42d9-9cfe-d5d1a8dc74fe.png)

Test .asice file attached.
[forgery7.zip](https://github.com/open-eid/DigiDoc4-Client/files/9811450/forgery7.zip)

**Comment by metsma** [comment]
This should be in open-eid/libdigidocpp.
OCSP can contain 1 to N references to certificates (rfc6960).
If we cannot find suitable reference to certificate in OCSP then it is classified to UNKNOWN status.
