### ISSUE TITLE
Winget install

### ISSUE THREAD

**Issue by Niks218** [open-eid/DigiDoc4-Client#1198]
Hi! While installing DigiDoc4 client via winget application on Windows, it downloads and installs outdated v4.2.11. It was confusing because I couldn't use it because of expired certificates and also couldn't update it from within the application. Had to download the installer manually.

**Comment by kristelmerilain** [comment]
DigiDoc4 Client wasn't added to winget by us, it seems like someone from community added it to winget - https://github.com/microsoft/winget-pkgs/tree/master/manifests/r/RIA/DigiDoc4
Feel free to add new DigiDoc4 Client version to winget yourself.
Official builds are provided through official distribution point [id.ee](https://www.id.ee/en/article/install-id-software/).

**Comment by Niks218** [comment]
Oh, I'm sorry, thank you for the clarification.
