### ISSUE TITLE
Decrypt file command line on linux

### ISSUE THREAD

**Issue by dragonwebeu** [open-eid/DigiDoc4-Client#1205]
Hi all,

Is it possible to decrypt file with command line on linux using DigiDoc4-Client?  If Yes, can you pass pin in promt?

**Comment by kristelmerilain** [comment]
It is not possible to decrypt file with command line using DigiDoc4 Client.
Possible option is to use cdoc4j-util. More information is available [here](https://github.com/open-eid/cdoc4j/tree/master/util).
