### ISSUE TITLE
Error: expected class-name before ‘{’ token

### ISSUE THREAD

**Issue by pifagor87** [open-eid/DigiDoc4-Client#1240]
I use Ubuntu 22.04.3 LTS
When I run 
`cmake -B build -S .`
Everything works well.
When I run 
`cmake --build build`
I get errors
`
Building CXX object client/CMakeFiles/qdigidoc4.dir/DigiDoc.cpp.o
/home/pifagor/DigiDoc4-Client/client/DigiDoc.cpp:50:1: error: expected class-name before ‘{’ token
   50 | {
      | ^
/home/pifagor/DigiDoc4-Client/client/DigiDoc.cpp:53:14: error: ‘bool ServiceConfirmation::validateOnline() const’ marked ‘final’, but is not virtual
   53 |         bool validateOnline() const final {
      |              ^~~~~~~~~~~~~~
/home/pifagor/DigiDoc4-Client/client/DigiDoc.cpp: In lambda function:
/home/pifagor/DigiDoc4-Client/client/DigiDoc.cpp:518:47: error: no matching function for call to ‘digidoc::Container::openPtr(std::string, ServiceConfirmation*)’
  518 |                         b = Container::openPtr(to(file), &cb);
      |                             ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
In file included from /home/pifagor/DigiDoc4-Client/client/DigiDoc.h:24,
                 from /home/pifagor/DigiDoc4-Client/client/DigiDoc.cpp:20:
/usr/include/digidocpp/Container.h:68:39: note: candidate: ‘static std::unique_ptr<digidoc::Container> digidoc::Container::openPtr(const string&)’
   68 |     static std::unique_ptr<Container> openPtr(const std::string &path);
      |                                       ^~~~~~~
/usr/include/digidocpp/Container.h:68:39: note:   candidate expects 1 argument, 2 provided
/home/pifagor/DigiDoc4-Client/client/DigiDoc.cpp:532:110: error: no matching function for call to ‘digidoc::Container::openPtr(std::string, ServiceConfirmation*)’
  532 |                                                         parentContainer = std::exchange(b, Container::openPtr(to(tmppath), &cb));
      |                                                                                            ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
In file included from /home/pifagor/DigiDoc4-Client/client/DigiDoc.h:24,
                 from /home/pifagor/DigiDoc4-Client/client/DigiDoc.cpp:20:
/usr/include/digidocpp/Container.h:68:39: note: candidate: ‘static std::unique_ptr<digidoc::Container> digidoc::Container::openPtr(const string&)’
   68 |     static std::unique_ptr<Container> openPtr(const std::string &path);
      |                                       ^~~~~~~
/usr/include/digidocpp/Container.h:68:39: note:   candidate expects 1 argument, 2 provided
gmake[2]: *** [client/CMakeFiles/qdigidoc4.dir/build.make:999: client/CMakeFiles/qdigidoc4.dir/DigiDoc.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:324: client/CMakeFiles/qdigidoc4.dir/all] Error 2
gmake: *** [Makefile:156: all] Error 2
`

**Comment by metsma** [comment]
You need update libdigidocpp code

**Comment by pifagor87** [comment]
Hello @metsma , thanks for the answer
I install libdigidocpp, and then use " /usr/local/bin/digidoc-tool"
I get
`/usr/local/bin/digidoc-tool: symbol lookup error: /usr/local/bin/digidoc-tool: undefined symbol: _ZN7digidoc9Container7openPtrERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_15ContainerOpenCBE`

After I use 
`cmake --build build`
I get a new error 
`Linking CXX executable qdigidoc4
/usr/bin/ld: /tmp/ccDWUs1j.ltrans4.ltrans.o: in function `DigiDoc::open(QString const&)::{lambda()#1}::operator()() const':
<artificial>:(.text+0x127351): undefined reference to `digidoc::Container::openPtr(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, digidoc::ContainerOpenCB*)'
/usr/bin/ld: <artificial>:(.text+0x12777f): undefined reference to `digidoc::Container::openPtr(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, digidoc::ContainerOpenCB*)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [client/CMakeFiles/qdigidoc4.dir/build.make:1504: client/qdigidoc4] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:324: client/CMakeFiles/qdigidoc4.dir/all] Error 2
gmake: *** [Makefile:156: all] Error 2
`

**Comment by metsma** [comment]
> /usr/local/bin/digidoc-tool: symbol lookup error: /usr/local/bin/digidoc-tool: undefined symbol: _ZN7digidoc9Container7openPtrERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_15ContainerOpenCBE
Versions

This hints that you have built digidoc-tool from source and libdigidocpp.1 libarary is not to up to date.
Probably you need run `sudo ldconfig` or the /usr/local/lib is not in ld.config

**Comment by kristelmerilain** [comment]
Closing due inactivity, reopen if needed.
