### ISSUE TITLE
xml-security-c is getting retired

### ISSUE THREAD

**Issue by pxrb** [open-eid/DigiDoc4-Client#1275]
The homepage for xml-security-c, https://santuario.apache.org/cindex.html, notes that xml-security-c is getting retired. It is also noted in a news item on https://santuario.apache.org/index.html.

**Comment by kristelmerilain** [comment]
We are aware of xerces-c, xalan-c, xml-security-c library statuses.
There are some actions ongoing.
See https://github.com/open-eid/libdigidocpp/issues/510
Closing ticket here because this issue belongs to https://github.com/open-eid/libdigidocpp project

**Comment by pxrb** [comment]
So do I open a new issue on libdigidocpp or...?
