### ISSUE TITLE
TS URL outdated 

### ISSUE THREAD

**Issue by anpin** [open-eid/DigiDoc4-Client#1276]
Digidoc4 fails to sign any document due to `http://dd-at.ria.ee/tsa` being offline

![Screenshot from 2024-06-24 11-21-20](https://github.com/open-eid/DigiDoc4-Client/assets/6060545/13acde2d-1061-40cd-aae2-df57369a8147)

```console
> curl http://dd-at.ria.ee/tsa
curl: (6) Could not resolve host: dd-at.ria.ee
```

### Workaround 
As pointed in https://github.com/open-eid/libdigidocpp/issues/601 one shall set the time-stamping url to `https://eid-dd.ria.ee/ts`, then provide remote SSL certificate. 

The certificate could be obtained using following command 
```console
> openssl s_client -showcerts -connect eid-dd.ria.ee:443 </dev/null 2>/dev/null|openssl x509 -outform PEM > eid-ts.pem
```
![image](https://github.com/open-eid/DigiDoc4-Client/assets/6060545/c4e71cc2-c5d1-4ba7-b7ab-be62c23a818e)

**Comment by kristelmerilain** [comment]
This is now fixed with https://github.com/open-eid/libdigidocpp/pull/597 PR.

**Comment by flokli** [comment]
The workaround works, with this I'm able to sign.

However it seems the linked PR alone (rebuilding qdigidoc with this libdigidocpp) does not fix it (see https://github.com/open-eid/DigiDoc4-Client/issues/1281#issue-2465141695), and neither does it fix SmartID signing still being broken.
