### ISSUE TITLE
please update flatpak version

### ISSUE THREAD

**Issue by edmundlaugasson** [open-eid/DigiDoc4-Client#1289]
https://flathub.org/apps/ee.ria.qdigidoc4 has older version than officially available
https://www.id.ee/en/article/install-id-software/ shows update from 03.07.2024 and version 4.5.1.4455 but in flathub there is still in April last update - 4.5.1.0

**Comment by kristelmerilain** [comment]
DigiDoc4 Client wasn't added to flathub by us, it seems like someone from community added it.
I will leave this issue open so someone from the community can update the DigiDoc4 Client version in flathub.
Official builds are provided through official distribution point [id.ee](https://www.id.ee/en/article/install-id-software/).

**Comment by minosimo** [comment]
I am working on building the new dependencies, you are welcome to close this issue.
