### ISSUE TITLE
Rename executable to qdigidoc4

### ISSUE THREAD

**Issue by abitrolly** [open-eid/DigiDoc4-Client#163]
What's the point in the long `qdigidocclient` name if it could be just `qdigidoc4` or even `digidoc4` if no other software is being developed for the same purpose?

**Comment by uudisaru** [comment]
This is a new version of DigiDoc software and the executable really is `qdigidoc4`. `qdigidocclient` is the executable of [DigiDoc3 client](https://github.com/open-eid/qdigidoc).

**Comment by uudisaru** [comment]
Resolved by PR #195.
