### ISSUE TITLE
Rakendus ei paigalda veebilehitsejate pluginaid

### ISSUE THREAD

**Issue by martinvahi** [open-eid/DigiDoc4-Client#254]
# Vea kirjeldus

Kasutades värsket Winodws 10 VirtualBox virtuaalmasinat aadressilt

https://developer.microsoft.com/en-us/windows/downloads/virtual-machines

ei ole võimalik Firefox'ile ID-kaardi tuge saada ilma, et
kõigepealt installeeritaks ära DigiDoc3'e.

Vea sümptomite esile kutsumine:

1. Kloonida kordagi kävitamata Windowsi demo-virtuaalmasin.

2. Klooline ära installeerida uusim Mozilla Firefox.

3. Alla laadida DigiDoc4 uusim publitseerimisbinaar ning see kloonile ära installida.

4. Testida kloonil DigiDoc4 programmiga ID-kaardiga ühenduse saamist,
    näiteks passifoto allalaadimise näol. Järgmiste sammude eeldus on, et see õnnestub.
    _(Selleks tuleb VirtualBox'i kasutamise korral enne virtuaalmasina käivitamist
    virtuaalmasinale ID-kaardi lugeja kui USB-seadme juurdepääs lubada.)_

5. Kontrollida, et ega DigiDoc4 publitseerimisbinaar pole FireFox'i pluginaid ära installeerinud.
    **Minu juhtumi korral olid pluginad puudu, mitte vaid välja lülitatud, vaid just PUUDU.**

6. Kasutades klooni proovida ID-kaadiga kuhugi sisse logida. 
    **Kuna pluginaid ei installitud, siis see põrub.**

7. Kloonile ära installida DigiDoc3, kasutades DigiDoc3 publitseerimisbinaari.

8. Kloonil tööle tõmmata DigiDoc4 publitseerimisbinaar ning valida valikutest "Parandamine".

9. Lülitada Firefox'il sisse seal nüüd olemas olevad ID-kaardi pluginad.

10. Üritada kuhugi ID-kaardiga sisse logida ning 
    kui ID-kaart on lugejas, parool/pin on õige ning  
    teenus toimib, siis sisse logimine õnnestub.

# Lisasoovitus

Enne publitseerimist võiksite puhta virtuaalmasinaga testid läbi teha. 
Kuna ID-kaardi projekt on avatud tarkvara projekt, siis 
vähemalt alguses saab osa testidest tasuta jooksutada 

https://www.travis-ci.org/

serveritel kuid **kuna ID-kaardi projekt on e-Estonia suur lipulaev, siis oleks kultuuriliselt
täielik ämber piirduda tolle teenuse tasuta kontoga, mistõttu kultuuriliselt
oleks viisakas ID-kaardi testimiseks sealt ikkagi mingi natuke vingema 
rahaga, näiteks 500€/kuus, konto osta, eriti arvestades, et nad peavad ju
avatud tarkvara testimise masinaid tasuta üleval.**
Seda tasuta võimalust on ID-kaardi projekti korral viisakas
kasutada vaid alguses, et bürokraatia-vabamalt teenuse kasutus püsti seada,
et siis asja tööle saades üle minna tasulisele kontole. 
travis-ci üheks võtmefraasiks ID-kaardi projekti korral on: "Clean VMs for every build"

Ma vaatasin, et neil hinnakirja üleval pole, aga pakkuge ise neile seda 500€/kuus varianti, või prestiiži pärast ehk 1000€/kuus varianti. Eestis on maksukoormus nii räige, riigi-sektor laristab nii mis hirmus, mistõttu ei ole patt osa sellest meeletust raha hunnikust "tasuta bussisõidu" globaalsele analoogile kulutada. Sama lugu tegelikult GitHub'iga. Loodan, et Te ikka midagi neile maksate, sõltumata sellest, et avatud tarkvara projekte seal ametlikult tasuta majutatakse. Arvan, et sümboolne 100€/kuus on GitHub'ile antud juhtumil sobiv, sest GitHub ju eriti CPU-aega ei kuluta ja meeletuid kloonimisi ei tee. Kui see näib ikka Teie silmis raha laristamisena, siis meenutan Teile meie helde e-Riigi Riigikogulaste kuluhüvitiste teemat, kus kulühüvitised on nüüdseks lausa mitte-avalikud, et oleks raskem teada, milline riigikogulane oma naisele auto on liisinud.

**Comment by martinvahi** [comment]
Veel üks kummaline tähelepanek. Nimelt, kui kohe pärast
virtuaalmasina restarti avada DigiDoc4, nõnda, et kaart on lugejas
ja lugeja on virtuaalmasinas jooksva Windowsi USB seadmete loetelus olemas,
siis DigiDoc4 ei suuda kaardi andmeid lugeda. 
Seejärel sulgen DigiDoc4, ilma, et kaarti ega kaardilugejat
füüsiliselt üldse puutuks, avan samas virtuaalmasinas 
DigiDoc3 kaardihaldusvahendi ja see loeb kaardilt 
andmed välja. Seejärel panen DigiDoc3 kinni, ilma, et
kaarti ega kaardilugejat füüsiliselt üldse puutuks, ning
avan uuesti samas virtuaalmasinas DigiDoc4 ning nüüd
loeb DigiDoc4 kah kaardi andmed välja.

**Comment by metsma** [comment]
DigiDoc4 ja DigiDoc3 on ainult desktop rakendused ja nendel ei ole mingit seost browseritega.
Täieliku nimekirja komponentidest leidab siit https://github.com/open-eid/org/wiki.
Rohekm lugemist kogu baastarkvara metapaki sisust ja arhitektuurist saab lugeda siit http://open-eid.github.io/

**Comment by martinvahi** [comment]
> DigiDoc4 ja DigiDoc3 on ainult desktop rakendused ja 
> nendel ei ole mingit seost browseritega.
> Täieliku nimekirja komponentidest leidab siit https://github.com/open-eid/org/wiki.

Tänan vastuse eest. Kui DigiDoc4 ja DigiDoc3 ei oma mingit
seost veebilehitsejatega, siis palun kas Te võiksite täpsustada, kus aadressil
asub see publitseerimis-binaar, mida "vanaema" või "tädi_Maali"
saab oma Windowsi arvutisse ära installides oma veebilehitseja
sellisesse seisu, et sellega saab eesti.ee portaali ID-kaardiga sisse logida?

Kunagi ammu-ammu ma tegin e-postitsi ettepaneku, et kuna 
veebilehitsejate pluginate ja muude seadistuste sobivasse
seisu panemine on niivõrd tükk tegemist, et tava-kasutajad
sellega hakkama ei saa, siis võiks ID-kaardi-tarkvara arendajad
selle riigi jaoks ülitäthsa ja seetõttu ka miljonite eurodega rahastatud
projekti raames luua TorBrowser'i sarnase kombineeritud
paketi, niiöelda ID-kaardi-veebilehitseja, mille installimisel on 
see juba koos kõigi vajalike pluginatega, mis on sobivalt sisse 
lülitatud. Mingil perioodil, mil DigiDoc4 ei olnud veel publitseeritud,
oli olukord selline, et mina IT-inimesena pidin helistama ID-kaardi
tugi-telefonile, kust siis öeldi mulle mingi rida Windowsi versiooni
spetsiifilisi veidrusi, mida ma pidin ära tegema, et ID-kaardi-tarkvara 
tööle saada. Kui TorBrowser'i sarnase projekti valmistamine Teil
seal nende miljonite eurode suuruse rahastuse korral ÜLE JÕU KÄIB,
siis äärmisel juhul võiksite Te vähemalt valmis virtuaalmasinat
pakkuda, näiteks VirtualBox'i virtuaalmasinajälejndit, kus kõik ära on 
seadistatud.

Teate, tõesti, riigiametnikul on tema arvuti seadistamiseks kasutada
IT-osakonna spetsialistid, aga tavalisel "tädi_Maalil" ja kodu-kasutajal
ju ei ole võtta seda IT-osakonda, kes kogu selle jukerdamisega tegeleb.
Ka pole ma kuulnud, et oleks pakutud "vaata_Maailma" projekti sarnast
IT-abi, kus inimene saaks minna oma läpakaga kuhugi kontorisse ja 
tal pandaks seal tasuta ID-kaardi tarkvara ja kõik vajalikud "pluginad" tööle.
Kunagi käisin välja idee, et ma võiks ise mingi projekti raha eest 
pensionäridele ja muudele "tädi_Maalidele" sellist teenust osutada,
aga selle jaoks raha ei leitud. Küll aga leidis näiteks Tallinna linn raha
vähemalt 15000EUR'i jääskulptuuride jaoks ning arvestatav summa läks
Tallinna linnal ka "ülemiste mehikese" jaoks. Ehk siis, propaganda-jama jaoks
raha leidub, aga inimeste reaalseks aitamiseks isegi väiksemaid summasid
ei leidu ja isegi Teie meeskond, mis on hästi rahastatud, oma enda meeskonna
töö raames kodukasutajate peale, väga pehmelt öeldes, "üleliia palju" ei kipu mõtlema.

Tõesti oleks hea teada, kus on see kodukasutajatele mõeldud binaar,
mis siis kogu seadistustöö ära teeb. Või tunnistategi avalikult, et
kodukasutajad "närigu muru", riigiametnikel on IT-osakond abiks ja  
erafirmadel kontori võrku hooldav IT-firma abistab?

Jutt, et kodukasutajatele on ID-kaardi tugi-telefon, on tore. Hea, et see
abi-liin eksisteerib, aga esiteks, selle abiliini eest küsitakse minutitasu,
nagu meil maksu-koorem eestis liiga väike oleks, ning teiseks, 
tava-inimene, kellest osadel on raskusi isegi arvuti-kasutuse ABCga,
ei suuda selliste pool-tehniliste juhiste järgi tegutseda. Minul kui
elukutselisel tarkvara-arendajal oli sellest ID-kaardi abiliinist tõesti
abi(ma ei tea kõiki Windows versioonispetsiifilisi veidrusi, sõltumata sellest,
et tarkvaraarendajana töötan) aga ma ei kujuta ette, et 
tava-kasutaja selliste juhiste järgi ID-kaardi oma arvutis kasutusvalmis saab.
Kusjuures, rõhutan, et Teil ei ole seal ID-kaardi-tarkvara-arenduse
meeskonnas probleemi rahastusega. Tuletageim kasvõi meelde
neid meeletuid summasid, mida viimase ID-kaardi-kriisi aegu hoobilt
sinna projekti loobiti. Seega, probleem ei ole rahastuse taga,
vaid POLIITILISE OTSUSE TAGA, et kas kodukasutajaid nähakse
lõppkasutajatena või nähakse lõppkasutajatena ainult
sellist seltskonda, kel on mingi võimalus IT-tuge kasutada.

Tänan lugemast ja tänan vastuste eest.

**Comment by tynisr** [comment]
Tere 

"Te võiksite täpsustada, kus aadressil asub see publitseerimis-binaar, mida "vanaema" või "tädi_Maali"
saab oma Windowsi arvutisse ära installides oma veebilehitseja sellisesse seisu, et sellega saab eesti.ee portaali ID-kaardiga sisse logida?"

eID Baastarkvara koos paigaldamisjuhistega asub https://installer.id.ee/?lang=est

**Comment by martinvahi** [comment]
> eID Baastarkvara koos paigaldamisjuhistega asub https://installer.id.ee/?lang=est

Tänan vastuse eest. Mul on hea meel näha, et lootust on. 
Palun täiendage oma juhiseid aadressil 

https://installer.id.ee/?lang=est&os=windows

väitega, et lisaks seal kirjeldatule tuleb tööle tõmmata ka 
skript, mille kasutus on kirjeldatud aadressil 

https://installer.id.ee/?lang=est

Nagu minu praegusest veaaruandest näha, vaid nendest juhistest, 
millest mina lähtusin, jääb väheks.

Tänan.
