### ISSUE TITLE
Alla laetava pildi mõõtmed on vaid 120px*150px

### ISSUE THREAD

**Issue by martinvahi** [open-eid/DigiDoc4-Client#256]
Võrdluseks, DigiDoc3 korral on samalt ID-kaardilt 
alla laetava, visuaalselt samasuguse, pildi mõõtmed

    400px*528px

Mõlemal juhtumil kasutasin DigiDoc'i publitseerimisbinaare.
Operatsioonisüsteemiks oli Windowns 10 VirtualBox'i virtuaalmasin 
aadressilt 

https://developer.microsoft.com/en-us/windows/downloads/virtual-machines

Tänan lugemast.

**Comment by uudisaru** [comment]
Parandatud / Fixed with PR https://github.com/open-eid/DigiDoc4-Client/pull/257
