### ISSUE TITLE
compilation error 

### ISSUE THREAD

**Issue by whysthatso** [open-eid/DigiDoc4-Client#26]
Hey
i'm trying to compile the client on arch linux.
`cmake` runs successfully, all dependencies are installed.

make produces this error:

```
In file included from /home/andreas/bin/qdigidoc/common/QBreakPad.cpp:60:0:
/home/andreas/bin/qdigidoc/common/google-breakpad/src/client/linux/handler/exception_handler.h:194:21: error: field ‘context’ has incomplete type ‘google_breakpad::ucontext’
     struct ucontext context;
                     ^~~~~~~
/home/andreas/bin/qdigidoc/common/google-breakpad/src/client/linux/handler/exception_handler.h:194:12: note: forward declaration of ‘struct google_breakpad::ucontext’
     struct ucontext context;
            ^~~~~~~~
make[2]: *** [common/CMakeFiles/qdigidoccommon.dir/build.make:921: common/CMakeFiles/qdigidoccommon.dir/QBreakPad.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:196: common/CMakeFiles/qdigidoccommon.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
i found a similar error in another project:
https://aur.archlinux.org/packages/megasync/

the author points to a possible changed type; that 'ucontext' type is no longer available (see sys/ucontext.h), it was replaced with 'ucontext_t'

maybe that helps.

can i provide any more information to help solving this?

or alternatively is there another suggested way to get digidoc client running in any other distro than ubuntu?

**Comment by uudisaru** [comment]
Officially we support only Linux versions based on Debian (Ubuntu), but you could try to compile qdigidoc without Breakpad support:

`cmake -DBREAKPAD="" ..`

Also please note that this is repository for new Digidoc 4 client (alpha sw and currently not usable), you seem to be referencing Digidoc3 client (https://github.com/open-eid/qdigidoc).

**Comment by whysthatso** [comment]
ah, damn, wrong repo. i also just found the AUR entry. i wish there would have been a keyword in my search that would have matched that entry :)

thanks anyway.
