### ISSUE TITLE
macOS-il on failide ikoonid “Digidoc *3*“ tekstiga

### ISSUE THREAD

**Issue by joellimberg** [open-eid/DigiDoc4-Client#265]
Näiteks:

https://github.com/open-eid/DigiDoc4-Client/blob/master/client/mac/Resources/asic.icns

<img width="366" alt="screen shot 2018-06-25 at 23 21 38" src="https://user-images.githubusercontent.com/875872/41873759-a2f00162-78ce-11e8-95f8-1f9769db0bca.png">

**Comment by markus-kullerkup** [comment]
Kirjeldatud viga saab parandatud järgmises väljalaskes.
Described issue will be fixed in the next release.
