### ISSUE TITLE
qdigidoc4 käivitamine ebaõnnestub Ubuntu Linux 18.04 LTS, 64bit

### ISSUE THREAD

**Issue by myymi** [open-eid/DigiDoc4-Client#278]
Ikoonil klõpsates tekib tegumiribale korraks ikoon ning kaob kohe.
Käsurealt qdigidoc4 välja kutsudes saan sellise väljundi:

bash$: qdigidoc4 
Chache configuration serial: 64
Bundled configuration serial: 64
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QSigner(0x564c5b39d360), parent's thread is QThread(0x564c5afe4a40), current thread is QSigner(0x564c5b39d360)
Loading: "opensc-pkcs11.so"
"OPENSC PROJECT                   (2.20)" 
"OPENSC SMARTCARD FRAMEWORK       (0.17)" 
Flags: 0
qdigidoc4.QSigner: Disconnected from card "loading"
qdigidoc4.QSmartCard: Polling
qdigidoc4.QSmartCard: Poll ""
qdigidoc4: symbol lookup error: /usr/lib/x86_64-linux-gnu/libdigidocpp.so.1: undefined symbol: _ZN11xalanc_1_1114XPathEvaluator10initializeERN11xercesc_3_113MemoryManagerE

**Comment by metsma** [comment]
What is the version number of package xml-security-c?

**Comment by 4nd3r** [comment]
tõenäoliselt sama mis repos: https://packages.ubuntu.com/bionic/libxml-security-c17v5

kui lugeda https://github.com/open-eid/DigiDoc4-Client/issues/190#issuecomment-382492631, siis pakun, et kui paigaldada 1.7.3-4 (mitte build1 suffiksiga), siis lendab taas. 

komistasin ebastabiilse toote keskkonnas (debian sid) sama _undefined symbol_ teate otsa digidoc3 puhul. aitas viidatud kommentaaris nimetatud pakkide versioonidele downgrade. võib-olla aitab ka täna, võib-olla mitte. aga pikas plaanis ei ole see mõistlik viis elamiseks.

viga ise paistab olevat pigem distro pakendaja poolel, mitte konkreetselt digidociga seotud. ja kuna ubuntu imeb asju debianst, siis oleks vist mõistlik eelnevalt debiani raporteerida või mõlemasse paralleelselt. ise raporteerinud pole, sest pole täpselt uurida viitsinud kust viga tuleb - xalan, xerces või xml-security-c.

või kui saab sellest probleemist ümber digidoci poolel, oleks veel parem.

**Comment by myymi** [comment]
Tundub, et pigem oli viga minu süsteemis. Masin oli uuendatud 16.04 päält 18.04-ni ja kuigi väidetavalt peaks see kompott korrektselt toimima jääma, siis alati see nii ei ole, eriti pikalt kasutuses olnud masinas. Puhta installiga toimib kõik veatult. Tarkvaratükkide versioone kahjuks hetkel siia lisada enam ei saa, sest see install on ajalugu, ja seda mitte id-kaardi tarkvara pärast.

**Comment by metsma** [comment]
äkki ei muutnud seda /etc/apt/sources.list.d/ria-repository.list distro nime ära upgrade

**Comment by vershinin** [comment]
Btw, @metsma, I guess it is not correct solution to have your own opensc, and libxmlsecurity in your repo. I think it would be nice, if we ask Debian maintainer to build libxmlsecurity with xalan-c support and push it into debian central repo. What do you think?

**Comment by metsma** [comment]
Debian maintainer is unwilling to enable xalan support
https://bugs.launchpad.net/ubuntu/+source/xml-security-c/+bug/1269434
And updated opensc 0.18.0 with EstEID support is already imported to upcoming ubuntu 18.10 repo.

**Comment by jyrgenh** [comment]
Xubuntu 18.04

Eelnevalt oli paigaldatud https://installer.id.ee/media/install-scripts/install-open-eid.sh millega vana digidoci klient töötas.
Juhendi järgi (https://www.id.ee/index.php?id=38642) paigaldasin beta kliendi:

- https://installer.id.ee/media/id2019/Ubuntu/AWP_5.3.0_SR5_Estonia_1804_et-EE_amd64.deb
- https://installer.id.ee/media/id2019/Ubuntu/chrome-token-signing_1.0.8.637.BETA-1804_amd64.deb
- https://installer.id.ee/media/id2019/Ubuntu/qdigidoc4_4.1.0.787.BETA-1804_amd64.deb

qdigidoc4 käsurealt käivitades:
```
$ qdigidoc4 
qdigidoc4: symbol lookup error: qdigidoc4: undefined symbol: _ZN7digidoc9ExceptionC1EOS0_
```

Kellelgi mõtteid, kuidas sellest edasi pääseda?

**Comment by monperrus** [comment]
I'm hit by this bug on Debian Testing.

It seems that I'll have to use Ubuntu in a VM to be able to use qdigidoc4 :disappointed:

**Comment by metsma** [comment]
Did you fix apt sources list file? Upgrade the distro name

**Comment by Dm1tro-in-da-world** [comment]
Oli sama viga. Ubuntu uuendatud 16.04 päält 18.04-ni.

Lahendus:
1. Uninstall script: https://installer.id.ee/media/install-scripts/uninstall-open-eid.sh
2. Install script: https://installer.id.ee/media/install-scripts/install-open-eid.sh
