### ISSUE TITLE
qdigidoc4 beta käivitamine ebaõnnestub Xubuntu 18.04 64bit

### ISSUE THREAD

**Issue by jyrgenh** [open-eid/DigiDoc4-Client#367]
Xubuntu 18.04

Eelnevalt oli paigaldatud https://installer.id.ee/media/install-scripts/install-open-eid.sh millega vana digidoci klient töötas.
Juhendi järgi (https://www.id.ee/index.php?id=38642) paigaldasin beta kliendi:

- https://installer.id.ee/media/id2019/Ubuntu/AWP_5.3.0_SR5_Estonia_1804_et-EE_amd64.deb
- https://installer.id.ee/media/id2019/Ubuntu/chrome-token-signing_1.0.8.637.BETA-1804_amd64.deb
- https://installer.id.ee/media/id2019/Ubuntu/qdigidoc4_4.1.0.787.BETA-1804_amd64.deb

qdigidoc4 käsurealt käivitades:
```
$ qdigidoc4 
qdigidoc4: symbol lookup error: qdigidoc4: undefined symbol: _ZN7digidoc9ExceptionC1EOS0_
```

**Comment by metsma** [comment]
https://www.id.ee/?lang=et&id=38683

**Comment by jyrgenh** [comment]
Ka seda lahendus proovitud ja tulemuseta.

**Comment by metsma** [comment]
Mis on su libdigidocpp ja xml-security-c versiooni numbrid

**Comment by jyrgenh** [comment]
```
$ sudo apt-cache policy libdigidocpp1
libdigidocpp1:
  Installed: 3.13.7.1377-1804
  Candidate: 3.13.7.1377-1804
  Version table:
 *** 3.13.7.1377-1804 500
        500 https://installer.id.ee/media/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

$ sudo apt-cache policy libxml-security-c17v5 
libxml-security-c17v5:
  Installed: 1.7.3-4build1RIA1
  Candidate: 1.7.3-4build1RIA1
  Version table:
 *** 1.7.3-4build1RIA1 500
        500 https://installer.id.ee/media/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     1.7.3-4build1 500
        500 http://ee.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
```

**Comment by metsma** [comment]
https://installer.id.ee/media/ubuntu/dists/bionic/main/binary-amd64/Packages
Depends: libdigidocpp-common (= 3.13.7.1377-1804), libc6 (>= 2.14), libdigidoc2, libgcc1 (>= 1:3.0), libssl1.1 (>= 1.1.0d), libstdc++6 (>= 7), libxalan-c111, libxerces-c3.2, libxml-security-c20, zlib1g (>= 1:1.1.4)

kas libxml-security-c20_2.0.1-1RIA2_amd64.deb pakk on installitud?

**Comment by jyrgenh** [comment]
Kontrollisin, jah see ka olemas:
```
$ sudo apt-cache policy libxml-security-c20
libxml-security-c20:
  Installed: 2.0.1-1RIA2
  Candidate: 2.0.1-1RIA2
  Version table:
 *** 2.0.1-1RIA2 500
        500 https://installer.id.ee/media/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by metsma** [comment]
Mis digidoc4 versioon on?

**Comment by metsma** [comment]
Kas käsurealt digidoc-tool käivitub?
