### ISSUE TITLE
Going from Google search result hides Linux choice

### ISSUE THREAD

**Issue by abitrolly** [open-eid/DigiDoc4-Client#401]
I am happily running Linux for more than a year already. Today I was looking for an update and followed the link from Google just to discover that there is no Linux version:

![image](https://user-images.githubusercontent.com/8781107/49274886-c2765800-f48a-11e8-8e30-0f3a410b17be.png)

The link there is https://installer.id.ee/?lang=eng&os=windows

![image](https://user-images.githubusercontent.com/8781107/49275289-e9815980-f48b-11e8-8621-643087be6184.png)

If I didn't know that there is Linux version beforehand, I would miss it. It took time to discover a small link at point 6 and then realize that URL is wrong.

![image](https://user-images.githubusercontent.com/8781107/49275338-15044400-f48c-11e8-8742-b11bfe0271cf.png)

Because autodetection didn't work while landing from Google, maybe there could a more prominent breadcrumb with OS selection and OS icons?

**Comment by metsma** [comment]
This is not related DigiDoc4 application. Please report to correct support channels

**Comment by abitrolly** [comment]
@metsma can you point to the correct support channel to discuss the distribution of the Linux binary from this repository?

**Comment by metsma** [comment]
From end of readme
Support

Official builds are provided through official distribution point installer.id.ee. If you want support, you need to be using official builds. Contact for assistance by email abi@id.ee or www.id.ee.
