### ISSUE TITLE
Sandboxed patch for digidoc4

### ISSUE THREAD

**Issue by Germano0** [open-eid/DigiDoc4-Client#402]
In qdigidoc3 ["building-in-sandboxed-environment" patch](https://github.com/open-eid/qdigidoc/wiki/DeveloperTips#building-in-sandboxed-environment), line
`qt5_add_resources( SOURCES images/images.qrc ${CMAKE_CURRENT_BINARY_DIR}/tr.qrc ${CMAKE_CURRENT_BINARY_DIR}/TSL.qrc )`
was replaced with
`qt5_add_resources( SOURCES images/images.qrc ${CMAKE_CURRENT_BINARY_DIR}/tr.qrc TSL.qrc )`

Now in DigiDoc4-client, instead of
`qt5_add_resources( SOURCES images/images.qrc ${CMAKE_CURRENT_BINARY_DIR}/tr.qrc ${CMAKE_CURRENT_BINARY_DIR}/TSL.qrc )`
we have
`qt5_add_resources( SOURCES images/images.qrc fonts/fonts.qrc ${CMAKE_CURRENT_BINARY_DIR}/tr.qrc ${CMAKE_CURRENT_BINARY_DIR}/TSL.qrc )`
that is almost the same, expect for `fonts/fonts.qrc`.

So what should be used as replacement, the old
`qt5_add_resources( SOURCES images/images.qrc ${CMAKE_CURRENT_BINARY_DIR}/tr.qrc TSL.qrc )`
or something that has`fonts/fonts.qrc` inside, like
`qt5_add_resources( SOURCES images/images.qrc fonts/fonts.qrc ${CMAKE_CURRENT_BINARY_DIR}/tr.qrc TSL.qrc )`
?
Thank you

**Comment by metsma** [comment]
Yes, keep the fonts

**Comment by metsma** [comment]
Created article how to modify build
https://github.com/open-eid/DigiDoc4-Client/wiki/DeveloperTips#building-in-sandboxed-environment
