### ISSUE TITLE
broken cmake/modules/VersionInfo.cmake from 4.2.0.43 tarball

### ISSUE THREAD

**Issue by glensc** [open-eid/DigiDoc4-Client#407]
using https://github.com/open-eid/DigiDoc4-Client/releases/download/v4.2.0/qdigidoc4_4.2.0.43.orig.tar.xz to build, results cmake (3.13.0) syntax error

```
CMake Error at cmake/modules/VersionInfo.cmake:73:
  Parse error.  Function missing ending ")".  End of file reached.
Call Stack (most recent call first):
```

this is caused by syntax error beginning of the file:
```cmake
 if( $ENV{BUILD_NUMBER} )
    set( BUILD_VER #{ENV["BUILD_NUMBER"]} )
 elseif(PROJECT_VERSION_TWEAK)
    set( BUILD_VER #{ENV["BUILD_NUMBER"]} )
 else()
    set( BUILD_VER #{ENV["BUILD_NUMBER"]} )
 endif()
 if(NOT BUILD_DATE)
    string(TIMESTAMP BUILD_DATE "%d.%m.%Y")
```

see:
- https://github.com/open-eid/cmake/pull/5#issuecomment-445734209
- https://github.com/open-eid/cmake/pull/5#issuecomment-445736907

i suspect the tarball was locally modified, as file with that content can't be found from git repository.

**Comment by metsma** [comment]
Please use this file 
https://github.com/open-eid/DigiDoc4-Client/releases/download/v4.2.0/qdigidoc4-4.2.0.tar.gz

**Comment by glensc** [comment]
not solved.

that file misses `cmake/modules`, if you make diff of the two tarballs.
