### ISSUE TITLE
Wiki not consistent concerning qt-common/CMakeLists.txt 

### ISSUE THREAD

**Issue by Germano0** [open-eid/DigiDoc4-Client#413]
In wiki
https://github.com/open-eid/DigiDoc4-Client/wiki/DeveloperTips#building-in-sandboxed-environment
the part

```
Comment out lines
https://github.com/open-eid/qt-common/blob/master/CMakeLists.txt#L19-L24
Replace line
https://github.com/open-eid/qt-common/blob/master/CMakeLists.txt#L25
qt5_add_resources( SOURCES ${CMAKE_CURRENT_BINARY_DIR}/config.qrc )
with
qt5_add_resources( SOURCES config.qrc )
```
is broken because it is not consistent with `qdigidoc4-4.2.0/common/CMakeLists.txt` content.
In particular in `qdigidoc4-4.2.0/common/CMakeLists.txt` there is no `qt5_add_resources( SOURCES ${CMAKE_CURRENT_BINARY_DIR}/config.qrc )` at line number 25, instead it is a line number 20, that should be commented as far it's said in

```
Comment out lines
https://github.com/open-eid/qt-common/blob/master/CMakeLists.txt#L19-L24
```

**Comment by metsma** [comment]
Updated wiki
