### ISSUE TITLE
Pärast beeta-versiooni kasutamist jääb aktiivseks test-keskkond

### ISSUE THREAD

**Issue by nostneji** [open-eid/DigiDoc4-Client#428]
Novembris installisin arvutisse EID tarkvara vastavalt juhenditele lehel https://www.id.ee/index.php?id=38642. Testisin EDEMIA testkaardiga ja kõik toimis.
Nüüd püüdsin installida samasse arvutisse uut ametlikku versiooni lehelt https://installer.id.ee/?lang=est (https://installer.id.ee/media/win/Open-EID-18.12.0.1819_x86.exe). Installimise käigus sain veateate/juhise, et eelnev versioon tuleb enne uue installimist eemaldada. Tegin seda ja järgnevalt uue EID tarkvara installeerimine õnnestus.
Kui ma nüüd püüdsin DigiDoc4 klienti kasutada, siis selgus, et uut asice konterinerit ei saa luua ja olemasolevate vaatamisel näidatakse, et "Allkiri on teadmata". Diagnostika alt on võimalik lugeda, et TSL_URL väärtuseks on https://open-eid.github.io/test-TL/tl-mp-test-EE.xml, millest teen järelduse, et DigiDoc4 klient on jäänud tööle test-režiimis.
Minu meelest on viga, et DigiDoc4 klient installides ei taga töökeskkonna kasutuselevõttu.
Teiseks ei leidnud ma pinnapealse otsimise tulemusel ka ühtegi juhendit selle kohta, kuidas ma tekkinud olukorda võiks käsitsi parandada ehk kuidas ma võiks määrateda seda, millises keskkonnas rakendus peaks töötama.

**Comment by kristelmerilain** [comment]
https://www.id.ee/index.php?id=38642 on saadaval juhend mida tuleb teha peale beta tarkvara kasutamist:
Windows - kustuta %APPDATA%\digidocpp ja %APPDATA%\RIA
macOS - kustuta ~/Library/Containers/ee.ria.qdigidoc4/Data/Library/Application Support/RIA/qdigidoc4/*
Ubuntu - kustuta kataloogid /.digidocpp/tsl ja /.local/share/RIA/qdigidoc4

**Comment by nostneji** [comment]
Tänan!
