### ISSUE TITLE
Un-necessary decimal representation of certificate serial in cert detail view

### ISSUE THREAD

**Issue by martinpaljak** [open-eid/DigiDoc4-Client#429]
Whenever it is needed in real life, the hex representation is sufficient (and more compact)

**Comment by metsma** [comment]
This is because pre-dates, when certificate serial numbers where short and every GUI implementation had own idea how to display serial number.
Today seems that all are using hex

**Comment by metsma** [comment]
Seems like this is already done in 3e5606ede2e19b358d68e4bba42090c64298da0e
