### ISSUE TITLE
qdigidoc4 needs missing symbols in libxml-security-c.so.17 and libdigidocpp.so.1

### ISSUE THREAD

**Issue by getreu** [open-eid/DigiDoc4-Client#434]
```
$ qdigidoc4
qdigidoc4: symbol lookup error: /usr/lib/x86_64-linux-gnu/libxml-security-c.so.17: undefined symbol: _ZNK11xalanc_1_118Function7executeERNS_21XPathExecutionContextEPNS_9XalanNodeERKNS_11XalanVectorINS_10XObjectPtrENS_31MemoryManagedConstructionTraitsIS6_EEEEPKN11xercesc_3_17LocatorE
```

Base system is Debian 9 with the following packages installed:

```
Package	Installed version	Latest version	Description
awp	5.3.0,.16.04.130		5.3,0.16.04.130	—	IDEMIA's AWP middleware installer:
chrome-token-signing	1:1.0.8.500-1604	1:1.0.8.500-1604	Estonian ID Card signing for Chrome and Firefox 
firefox-pkcs11-loader	3,13.0.1074-1604	3.13,0,1074-1604	Firefox PKCS#11 module loader 
firefox-pkes11-loader	3,13.0.1074-1604	3.13,0,1074-1604	Firefox PKCS#11 module loader 
libdigidoc-common	3,10.1.1212-1510	3.10.1,1212-1510	_DigiDoc digital signature library common files 
libdigidoc-common	3,10.1.1212-1510	3,10.1,1212-1510	_DigiDoc digital signature library common files 
libdigidoc-tools	3,10,1.1212-1510	3.10.1,1212-1510	_DigiDoc digital signature library tools 
libdigidoc2	3,10.1.1212-1510	3.10.1.1212-1510	DigiDoc digital signature library 
libdigidocpp-common	3,13.8.1379-1604	3.13.8.1379-1604	_DigiDoc digital signature library common files 
libdigidocpp-common	3,13.8.1379-1604	3.13.8.1379-1604	_DigiDoc digital signature library common files 
libdigidocpp-tools	3,13.8.1379-1604	3.13.8,1379-1604	_DigiDoc digital signature library tools 
libdigidocpp1	3,13.8.1379-1604	3.13.8.1379-1604	_DigiDoc digital signature library 
libxml-security-c17v5	L7.3-1RIAL	L7.3-1RIAL	C++ library for XML Digital Signatures (runtime) 
open-eid	18.12.0.1815-1604	18.12.0.1815-1604	This is elD Software metapackage 
open-eid	18.12.0.1815-1604	18.12.0.1815-1604	This is elD Software metapackage 
opensc	0.19.0-0RIA2	0.19.0-0RIA2	Smart card utilities with support for PKCS#15 compatible cards, 
opensc-pkesi1	0.19.0-0RIA2	0.19.0-0RIA2	Smart card utilities with support for PKCS#15 compatible cards 
adigidoc-tera	1.1.0,12-1604	1,1,0.12-1604	_ Estonian DDOC re-timestamping utility 
adigidoca	4.2.0.43-1604	——4,2.0.43-1604	—_ Estonian digital signature application
```

**Comment by getreu** [comment]
After having resolved the dependency issue above, the following shows up with 'libdigidocpp.so.1 `:

```
$ qdigidoc4
Chache configuration serial: 82
Bundled configuration serial: 79
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QSigner(0x19b4360), parent's thread is QThread(0x183d400), current thread is QSigner(0x19b4360)
qdigidoc4: symbol lookup error: /usr/lib/x86_64-linux-gnu/libdigidocpp.so.1: undefined symbol: _ZN11xalanc_1_1114XPathEvaluator10initializeERN11xercesc_3_113MemoryManagerE
```

**Comment by metsma** [comment]
See open-eid/libdigidocpp#143 and open-eid/libdigidocpp#134

**Comment by getreu** [comment]
Thank you for the links I read through carefully. Maybe I have missed something, but how does it solve my dependency problem? What additional packages do I have to install?
Since the latest upgrade my digidoc4 is broken and I need urgently sign documents.

**Comment by metsma** [comment]
It means Debian developer is unwilling compile libxml-security-c with libxalan-c dependency and RIA is  providing own binaries of libxml-security-c in repository https://installer.id.ee/media/ubuntu/pool/main/x/xml-security-c/

**Comment by getreu** [comment]
Your answer does not address my problem, neither my question.

As you can see from my above package list: I *did* install RIS's version of `libxml-security-c`.  Also all the package dependencies of  `libdigidocpp` are satisfied. As well as all other dependencies are. Nevertheless the linker is still not satisfied:

```
qdigidoc4: symbol lookup error: /usr/lib/x86_64-linux-gnu/libdigidocpp.so.1: undefined symbol: _ZN11xalanc_1_1114XPathEvaluator10initializeERN11xercesc_3_113MemoryManagerE
```

My still unanswered question is: what package is missing on my system?
It also means whatever this missing package on my system is: there is at least one package dependency missing in `qdigidoc4`. And this *is a bug*. 

Finally, could you give a reason why you closed my issue? Do you consider it irrelevant? Or solved?

**Comment by metsma** [comment]
I don't see such version https://packages.debian.org/stretch/libxalan-c-dev

**Comment by metsma** [comment]
> xalan (1.11-9~bpo9+1) stretch-backports; urgency=medium
>
>  * Rebuild for stretch-backports, using xerces 3.2.

I think this is the cause, you need also libdigidocpp compiled against xerces 3.2

**Comment by getreu** [comment]
Yes, I think so too. 
I updated my blog article about [installing Digidoc on Debian 9](https://blog.getreu.net/tags/digidoc/) to reflect the above workarounds.

**Comment by nekromoff** [comment]
Same issues on Ubuntu 18.04.3

qdigidoc4
qdigidoc4: symbol lookup error: qdigidoc4: undefined symbol: _ZTIN7digidoc9XmlConfV3E

qdigidocclient 
Chache configuration serial: 55
Bundled configuration serial: 55
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QSigner(0x55bb74b56280), parent's thread is QThread(0x55bb74981860), current thread is QSigner(0x55bb74b56280)
Loading: "opensc-pkcs11.so"
"OPENSC PROJECT                   (2.20)" 
"OPENSC SMARTCARD FRAMEWORK       (0.19)" 
Flags: 0
qdigidocclient: symbol lookup error: /usr/lib/x86_64-linux-gnu/libdigidocpp.so.1: undefined symbol: _ZN11xalanc_1_1114XPathEvaluator10initializeERN11xercesc_3_113MemoryManagerE

**Comment by getreu** [comment]
Maybe this help: [Digidoc Open-EID - Installation instructions for Debian 10 Buster](https://blog.getreu.net/projects/digidoc-open-eid--debian10/)
