### ISSUE TITLE
qdigidoc4 depends on `awp` which fails to install

### ISSUE THREAD

**Issue by getreu** [open-eid/DigiDoc4-Client#435]
this is a bug in the `postinst`-script of the `awp` package version 5.3.0,.16.04.130 and others.

# Patch
 
in file `awp_5.3.0.16.04.130_amd64.deb/deb://DEBIAN/postinst` 
replase the line

```
NSSDB=/$HOME/.pki/nssdb
```
with
```
NSSDB=/home/$SUDO_USER/.pki/nssdb
```

BTW

this package does not comply with package policies, as the package-installer should not install anything in the user's home directory.

**Comment by metsma** [comment]
open-eid/linux-installer#37
