### ISSUE TITLE
Unable to sign specific pdf filename

### ISSUE THREAD

**Issue by siimots** [open-eid/DigiDoc4-Client#463]
Ümbriku allkirjastamine ebaõnnestus

ASiC_E.cpp:348 Failed to sign BDOC container.
OCSP.cpp:119 Failed to send OCSP request

Kui failinimi lõppes ..."lep.muudatus.pdf", siis ei õnnestunud kuidagi pdfi allkirjastada, kui failinime lõpp muuta ..."lepingu muudatus.pdf", siis toimis ilusti allkirjastamine.

Kuigi mõne teise faili puhul ..."lep.muudatus.pdf" läks läbi. Kuna failid on salajased, siis konkreetset faili ei saa edasi saata arendajatele.

Keeleseaded: Estonian / 1257 (ANSI - Baltic)
Kasutajaõigused: Administraator
Baastarkvara: 18.12.0.1819
Rakenduse versioon: 4.2.0.42 (32 bit)
Operatsioonisüsteem: Windows 10 17763 (64 bit)

**Comment by tynisr** [comment]
Kas alati kasutati allkirjastamiseks sama kaarti ja sama arvutit/tarkvara versiooni?

**Comment by siimots** [comment]
Jah, sama arvuti.

Kui see fail ei töötanud, siis võtsin kohe järgmise faili ette ja sain allkirjastatud kiiresti.
Proovisin uuesti vanat faili, siis ei saanud ikka allkirjastada.
Pärast ümbernimetamist sai allkirjastada.

Pin koodi küsib kõik ilusti ära, aga "Allkirjastamine" ja 🔄 ikoon jäi väga kauaks ette ja siis viskas veateate.
Ümbriku allkirjastamine ebaõnnestus

ASiC_E.cpp:348 Failed to sign BDOC container.
OCSP.cpp:119 Failed to send OCSP request

**Comment by siimots** [comment]
Täna uuesti proovides toimis kõik okeilt.
Ei tea, siis miks eile seda veateadet viskas mitmeid kordi proovides kuni faili ümbernimetamiseni.

**Comment by tynisr** [comment]
OCSP teenus on selles võrrandis ka üks osapool.
Sulgen kuni probleem peaks uuesti ilmnema.
Kirjuta järgmine kord id.ee kaudu - saame küsida spetsiifilisemalt.

**Comment by ttiganik** [comment]
Mul oli sama viga osx 4.2.2.52 puhul kui faili nimi oli "avaldus maanteametile.docx". Kui muutsin nime "avaldus-maanteametile.docx", siis allkirjastamine õnnestus.

Kui peale seda muutsin nime tagasi "avaldus maanteametile.docx", siis allkirjastamine õnnestus ka selle esialgselt vigase nimega.
