### ISSUE TITLE
Can't view files with spaces in filename on Linux

### ISSUE THREAD

**Issue by rushmorem** [open-eid/DigiDoc4-Client#471]
When someone sends me a document with spaces in filename, I can't open it on Linux (NixOS). It says file does not exist. When I try to download the file instead so I can open it separately, the file seems to download fine but when I check file size it's 0 bytes so I can't even open it. I'm on v4.2.0 (the latest so far).

**Comment by smirnov** [comment]
I've just tested opening signed files with spaces and digidoc 4.2.1 seems to handle this just fine. Can you confirm that the behaviour reproduces itself still? If yes, please share how specifically do you open the files (what file manager do you use/how do you select the file for opening)

**Comment by rushmorem** [comment]
Oops! I forgot to close this. After I opened this issue, I asked the sender to resend without spaces in the filename. They sent again _with_ spaces but it worked so spaces were not the issue.
