### ISSUE TITLE
macos packages are missing

### ISSUE THREAD

**Issue by ristik** [open-eid/DigiDoc4-Client#490]
MacOS packages are missing from releases.
(no, macos apple appstore is not an answer, it requires one to accept a ridiculously verbose license agreement, then creating an apple id account, which is not trivial to accomplish without supplying valid credit card data)

**Comment by metsma** [comment]
They are there
https://github.com/open-eid/DigiDoc4-Client/releases/tag/v4.2.0
https://github.com/open-eid/DigiDoc4-Client/releases/download/v4.2.0/qdigidoc4_4.2.0.43.zip
