### ISSUE TITLE
Instructions for sandboxed builds seem to be outdated due to recent changes 4.2.1

### ISSUE THREAD

**Issue by smirnov** [open-eid/DigiDoc4-Client#491]
The links to required changes don't seem be current anymore:

https://github.com/open-eid/DigiDoc4-Client/wiki/DeveloperTips#building-in-sandboxed-environment

And I'm not quite sure how they'd be translated onto the new code, some advise could help on how to change the patching (and whether it's still required).

**Comment by metsma** [comment]
Updated qt-common links
