### ISSUE TITLE
Malware-like abusive "enterprise policy" installation of browser extensions

### ISSUE THREAD

**Issue by lietu** [open-eid/DigiDoc4-Client#495]
When I get the software from installer.id.ee it also forcefully installs browser extensions on e.g. Chrome without my explicit permission. These extensions are installed using malware-like "enterprise policies" so it is made near-impossible for me to uninstall them when I don't want them.

I use the software to sign and view signed documents. I can accomplish this perfectly fine using Mobile ID. I do not want, nor do I need any browser extensions, and you really do not have any reason, or right, to force me to run an extension on my browser that basically acts like malware and provides me with no benefits.

**Comment by Counter178** [comment]
Run installer again and remove all web extension supports.

**Comment by metsma** [comment]
Not related to DigiDoc4-Client and see open-eid/windows-installer there are options to disable plugins or on macOS you can skip browser extensions installation package
