### ISSUE TITLE
Some dialogs are unintelligible on Linux with dark theme

### ISSUE THREAD

**Issue by notpushkin** [open-eid/DigiDoc4-Client#496]
![Screenshot](https://user-images.githubusercontent.com/1298948/59277070-295da080-8c68-11e9-8278-917b7403fe15.png)

The white text colour is inherited from system Qt theme, and you can't see the text in some places. Also might want to check it against macOS Mojave+ dark mode as well. Thank you :)

**Comment by jaakristioja** [comment]
Well, white text on white background is not that bad. But when using themes with slightly grey foreground, the light grey text on white background is not only unintelligible, but literally makes me nauseous :dizzy_face: when I try to read it. I hope this doesn't cause people even problems worse than that...

![peavalu](https://user-images.githubusercontent.com/2684083/60657305-cc659c80-9e59-11e9-8a1b-ae78325a7a28.png)

**Comment by metsma** [comment]
Any hints how to reproduce?

**Comment by jaakristioja** [comment]
Run the utility under KDE with the the Breeze Dark (or Wonton Soup) color scheme applied in KDE settings.

**Comment by gagarine** [comment]
MacOS dark mode is supported only from Qt 5.12. Actual Digidoc stable release uses 5.9.6 at the moment.

**Comment by sander85** [comment]
> Any hints how to reproduce?

Switching Qt to dark theme is the easiest way.

Some texts are still shown, those where you have defined different color than the one from system. So if you don't plan to support dark themes then easy way to fix it is to define color for all texts.

**Comment by allanlaal** [comment]
issue present on Ubuntu Mate 20.10 (using a dark theme in mate-desktop) with libqt: 5.14.2

bgcolor is white and font color is light gray:

![Screenshot at 2021-03-09 15-54-44](https://user-images.githubusercontent.com/740826/110481382-2e2adf00-80f0-11eb-9b4a-6fe449f4e658.png)
