### ISSUE TITLE
Support the XDG Base Directory Specification

### ISSUE THREAD

**Issue by ettom** [open-eid/DigiDoc4-Client#514]
Currently qdigidoc4 stores its configuration in `$HOME/.digidocpp`. Instead of cluttering the home directory, it should follow the XDG Base Directory spec and store its configuration in its own directory under `$XDG_CONFIG_HOME` (`$HOME/.config/` by default). Cache should be stored in `$XDG_CACHE_HOME`.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by metsma** [comment]
DigiDoc4-Client follows XDG  spec.
$HOME/.digidocpp belongs to [open-eid/libdigidocpp](/open-eid/libdigidocpp) library

**Comment by muusik** [comment]
According to the XDG spec, given above:
 
> There is a single base directory relative to which user-specific configuration files should be written. This directory is defined by the environment variable $XDG_CONFIG_HOME.

Given that, I don't see how your assertion that DigiDoc4-Client follows XDG spec holds true.

**Comment by metsma** [comment]
Can you list files that DigiDoc4 creates to wrong place? if so then we need to create bug report to Qt.
And I repeat .digidocpp folder is [open-eid/libdigidocpp](https://github.com/open-eid/libdigidocpp) config files.

**Comment by muusik** [comment]
My mistake, I'm sorry. I failed to differentiate between libdigidocpp and DigiDoc4-Client and misunderstood your comment, which appears to be correct.

**Comment by metsma** [comment]
There is already related request  in  https://github.com/open-eid/libdigidocpp/issues/352
