### ISSUE TITLE
Application version check relies on travis build number, not present in the sources tarball.

### ISSUE THREAD

**Issue by smirnov** [open-eid/DigiDoc4-Client#529]
Currently DigiDoc4's update check is taking travis build number into consideration, which gives false positive "update available" notification when packages are not built on EID infrastructure, since build number is always 0.

I would expect that if no changes were made to the sources, then the application is not outdated and deprecation and update check should be taking git tag into account, since build numbers can differ by platform or, if build is part of the version, then generated tarball should also contain build sub-number, since it is relevant for the application versioning.

**Comment by metsma** [comment]
It is fixed upstream https://id.eesti.ee/config.json
"QDIGIDOC4-LATEST": "4.2.2.0",
