### ISSUE TITLE
Rename "DigiDoc client" to "DigiDoc"

### ISSUE THREAD

**Issue by gagarine** [open-eid/DigiDoc4-Client#592]
I don't think "client" is necessary. In the doc, it's often called "DigiDoc4". A lot of software are a client but rarely "client" are in their name.

![Screenshot 2019-11-04 at 11 46 25](https://user-images.githubusercontent.com/164074/68112089-433e9f00-fef9-11e9-9f8a-a14ac31f04da.png)

![Screenshot 2019-11-04 at 11 54 32](https://user-images.githubusercontent.com/164074/68112392-e42d5a00-fef9-11e9-8620-4fb1f2242241.png)

**Comment by kristelmerilain** [comment]
Thank you for the suggestion.
Currently there are no plans to address this issue.
