### ISSUE TITLE
After deleting a container the windows title is not refreshed

### ISSUE THREAD

**Issue by gagarine** [open-eid/DigiDoc4-Client#593]
Dragging a file will change the window's title:
![Screenshot 2019-11-04 at 11 57 30](https://user-images.githubusercontent.com/164074/68112633-6cabfa80-fefa-11e9-9052-2cce41fe705d.png)

But removing it should reset the windows title yet the title stay:
![Screenshot 2019-11-04 at 11 57 37](https://user-images.githubusercontent.com/164074/68112695-936a3100-fefa-11e9-8bfa-f0f8ba257d14.png)

As a side note, MacOS does not allow anymore reading the title of the window by another program. But I think windows still allow that.  Sometimes file name can contain sensitive information like "contract with company X". Are you sure it's 100% safe to expose the file name in the window's title?

**Comment by kristelmerilain** [comment]
#575
