### ISSUE TITLE
Opening new windows as no effect (MacOS)

### ISSUE THREAD

**Issue by gagarine** [open-eid/DigiDoc4-Client#595]
Cliquing on new windows has no effect.
![Screenshot 2019-11-04 at 12 11 26](https://user-images.githubusercontent.com/164074/68113351-5141ef00-fefc-11e9-8f34-77992766b33e.png)

P.S. This should be renamed "New Windows" for OS consistency.

**Comment by kristelmerilain** [comment]
Was fixed in #698
