### ISSUE TITLE
Improve the menu for accessibility

### ISSUE THREAD

**Issue by gagarine** [open-eid/DigiDoc4-Client#596]
The MacOS global menu is an important tool for accessibility. A lot of accessibility tools allow you to quickly navigate the menu. It's also a good tool for feature discovery. Today Dididoc's menu is very poor:
![Screenshot 2019-11-04 at 12 15 18](https://user-images.githubusercontent.com/164074/68113667-f5c43100-fefc-11e9-8706-124e8c752a1b.png)

Main actions should be listed in the global menu. Especially actions related to files.

Also, every MacOS app needs a "Help" menu.

https://doc.qt.io/qt-5/qmenubar.html 
 
https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-bar-menus/

**Comment by kristelmerilain** [comment]
#705
