### ISSUE TITLE
Use the native MacOS toolbar instead of left sidebar

### ISSUE THREAD

**Issue by gagarine** [open-eid/DigiDoc4-Client#597]
MacOS's toolbar provides convenient access to frequently used commands 
https://developer.apple.com/design/human-interface-guidelines/macos/windows-and-views/toolbars/. 

![image](https://user-images.githubusercontent.com/164074/68115434-10000e00-ff01-11e9-8286-0b95c83a4444.png)
QT provides a wrapper for this native element: https://doc.qt.io/qt-5/qmactoolbar.html

Then the present left sidebar can be moved in the standard toolbar.
![Screenshot 2019-11-04 at 12 40 43](https://user-images.githubusercontent.com/164074/68115373-f2cb3f80-ff00-11e9-9c9a-f466fb2413f2.png)

**Comment by kristelmerilain** [comment]
Thank you for the suggestion.
Currently there are no plans to address this issue.
