### ISSUE TITLE
Crashing on Ubuntu 18.04.3, undefined symbol

### ISSUE THREAD

**Issue by nekromoff** [open-eid/DigiDoc4-Client#626]
qdigidoc4
qdigidoc4: symbol lookup error: qdigidoc4: undefined symbol: _ZTIN7digidoc9XmlConfV3E

qdigidocclient 
Chache configuration serial: 55
Bundled configuration serial: 55
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QSigner(0x55bb74b56280), parent's thread is QThread(0x55bb74981860), current thread is QSigner(0x55bb74b56280)
Loading: "opensc-pkcs11.so"
"OPENSC PROJECT                   (2.20)" 
"OPENSC SMARTCARD FRAMEWORK       (0.19)" 
Flags: 0
qdigidocclient: symbol lookup error: /usr/lib/x86_64-linux-gnu/libdigidocpp.so.1: undefined symbol: _ZN11xalanc_1_1114XPathEvaluator10initializeERN11xercesc_3_113MemoryManagerE

**Comment by metsma** [comment]
Your libdigidocpp1 package is not uptodate.
Run apt install libdigidocpp1 and install latest version.
qdigidocclient is unsupported on 18.04

**Comment by nekromoff** [comment]
It is up to date for Ubuntu LTS.
Reading state information... Done
libdigidocpp1 is already the newest version (3.14.1.1388-1804).
libdigidocpp1 set to manually installed.

**Comment by nekromoff** [comment]
Based on this - Ubuntu 18.04 is supported:
![image](https://user-images.githubusercontent.com/8550349/72384199-37533280-371d-11ea-8744-87a89703998c.png)

**Comment by nekromoff** [comment]
Ran the install script again and now it seems to be working fine.

Closing.
