### ISSUE TITLE
Could not build on Windows

### ISSUE THREAD

**Issue by hsynff** [open-eid/DigiDoc4-Client#670]
I'm following these steps for building DigiDoc4-CLient on Windows: 
[https://github.com/open-eid/DigiDoc4-Client#windows](url)

But I get error when I call 
    `cmake -G"NMake Makefiles" -DQt5_DIR="C:\Qt\5.9.8\msvc2015\lib\cmake\Qt5" ..`

    `CMake Error at C:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
      Could NOT find LibDigiDocpp (missing: LIBDIGIDOCPP_LIBRARY
      LIBDIGIDOCPP_INCLUDE_DIR) (Required is at least version "3.13.8")
    Call Stack (most recent call first):
      C:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
      cmake/modules/FindLibDigiDocpp.cmake:20 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
      CMakeLists.txt:18 (find_package)

    -- Configuring incomplete, errors occurred!
    See also "C:/Users/user/Documents/Projects/DigiDoc4- 
      Client/build/CMakeFiles/CMakeOutput.log".
       See also "C:/Users/user/Documents/Projects/DigiDoc4- 
      Client/build/CMakeFiles/CMakeError.log".`

I've tried with libdigidoc versions 3.13.8 and 3.14.1 but results are the same.

**Comment by karl80038** [comment]
You need to add -DLIBDIGIDOCPP_LIBRARY and -DLIBDIGIDOCPP_INCLUDE_DIR parameters at the end of your cmake command (or use environment variables). In the first parameter, you tell the compiler where the digidocpp.lib file is located and in the second parameter you provide a path to libdigidocpp's Include folder. By default, libdigidocpp is installed in C:\Program Files (x86)\libdigidocpp . Make sure you also have OpenSSL installed (it automatically registers environment parameters so the compiler usually finds it automatically). You should also at least use QT 5.12.5, as the developers no longer use QT5.9 and as such the code may not compile and/or the compiled binary might not run properly.
Example:
cmake -G"NMake Makefiles" -DQt5_DIR="C:\Qt\5.12.6\msvc2015\lib\cmake\Qt5" -DLIBDIGIDOCPP_LIBRARY="C:\Program Files (x86)\libdigidocpp\x86\digidocpp.lib" -DLIBDIGIDOCPP_INCLUDE_DIR="C:\Program Files (x86)\libdigidocpp\include"  ..

If you are compiling a 64-bit version, substitute the library path with: "C:\Program Files (x86)\libdigidocpp\x64\digidocpp.lib"

**Comment by metsma** [comment]
And if you are building debug mode use digidocppd.lib

**Comment by karl80038** [comment]
I apologize, but my example script has a typo. Guess I should be more careful next time. The mistake lies in that QT 5.12.x no longer supports Visual C++ 2015 and requires at least Visual Studio 2017. I'd also like to thank metsma for reminding to use the debug library when building a debug version.
Also the script I wrote only applies when compiling a 32-bit application. There is a separate directory for the 64-bit version (msvc2017_64).
So the correct example when compiling a 32-bit would be:
cmake -G"NMake Makefiles" -DQt5_DIR="C:\Qt\5.12.6\msvc2017\lib\cmake\Qt5" -DLIBDIGIDOCPP_LIBRARY="C:\Program Files (x86)\libdigidocpp\x86\digidocpp.lib" -DLIBDIGIDOCPP_INCLUDE_DIR="C:\Program Files (x86)\libdigidocpp\include" ..

If we want to compile a 64-bit version, we should be using 64-bit libraries QT too:
cmake -G"NMake Makefiles" -DQt5_DIR="C:\Qt\5.12.6\msvc2017_64\lib\cmake\Qt5" -DLIBDIGIDOCPP_LIBRARY="C:\Program Files (x86)\libdigidocpp\x64\digidocpp.lib" -DLIBDIGIDOCPP_INCLUDE_DIR="C:\Program Files (x86)\libdigidocpp\include" ..

Like metsma said, if compiling a Debug build is desired, digidocppd.lib must be used in place of digidocpp.lib.

**Comment by kristelmerilain** [comment]
Closing due inactivity, reopen if needed.
