### ISSUE TITLE
CMake fails to configure with QT 5.12.7, with QT 5.12.6 and (possibly even earlier) CMake configures successfully

### ISSUE THREAD

**Issue by karl80038** [open-eid/DigiDoc4-Client#701]
Hello! I'm currently facing an issue, where CMake fails to configure when using QT 5.12.7. 
I'm building the binary using Windows 10 Pro x64 1909 with Visual Studio 2019 ver. 16.5.1
F:\digidoc\DigiDoc4-Build\x86>cmake -G"NMake Makefiles" "-DCMAKE_BUILD_TYPE=Release" -DQt5_DIR="F:\Qt\5.12.7\msvc2017\lib\cmake\Qt5" -DLIBDIGIDOCPP_LIBRARY="C:\LIBDIGIDOCPP\X86\DIGIDOCPP.LIB" -DLIBDIGIDOCPP_INCLUDE_DIR="C:\LIBDIGIDOCPP\INCLUDE" F:\digidoc\DigiDoc4-Client
-- The C compiler identification is MSVC 19.25.28611.0
-- The CXX compiler identification is MSVC 19.25.28611.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx86/x86/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx86/x86/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args`
  (PKCS11_Module) does not match the name of the calling package (PKCS11).
  This can lead to problems in calling code that expects `find_package`
  result variables (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindPKCS11.cmake:22 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:18 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PKCS11_Module: opensc-pkcs11.dll
-- Found LibDigiDocpp: C:/libdigidocpp/x86/digidocpp.lib (Required is at least version "3.14.3")
-- Found LDAP: C:/Program Files (x86)/Windows Kits/10/Lib/10.0.18362.0/um/x86/Wldap32.Lib
-- Found OpenSSL: optimized;C:/Program Files (x86)/OpenSSL-Win32/lib/VC/libcrypto32MD.lib;debug;C:/Program Files (x86)/OpenSSL-Win32/lib/VC/libcrypto32MDd.lib (found version "1.1.1d")
CMake Error at F:/Qt/5.12.7/msvc2017/lib/cmake/Qt5Core/Qt5CoreMacros.cmake:211 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  F:/Qt/5.12.7/msvc2017/lib/cmake/Qt5Core/Qt5CoreMacros.cmake:281 (_QT5_PARSE_QRC_FILE)
  common/CMakeLists.txt:11 (qt5_add_resources)

CMake Error at F:/Qt/5.12.7/msvc2017/lib/cmake/Qt5Core/Qt5CoreMacros.cmake:211 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  F:/Qt/5.12.7/msvc2017/lib/cmake/Qt5Core/Qt5CoreMacros.cmake:281 (_QT5_PARSE_QRC_FILE)
  common/CMakeLists.txt:44 (qt5_add_resources)

CMake Error at F:/Qt/5.12.7/msvc2017/lib/cmake/Qt5Core/Qt5CoreMacros.cmake:211 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  F:/Qt/5.12.7/msvc2017/lib/cmake/Qt5Core/Qt5CoreMacros.cmake:281 (_QT5_PARSE_QRC_FILE)
  client/CMakeLists.txt:14 (qt5_add_resources)

CMake Error at F:/Qt/5.12.7/msvc2017/lib/cmake/Qt5Core/Qt5CoreMacros.cmake:211 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  F:/Qt/5.12.7/msvc2017/lib/cmake/Qt5Core/Qt5CoreMacros.cmake:281 (_QT5_PARSE_QRC_FILE)
  client/CMakeLists.txt:14 (qt5_add_resources)

CMake Error at F:/Qt/5.12.7/msvc2017/lib/cmake/Qt5Core/Qt5CoreMacros.cmake:211 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  F:/Qt/5.12.7/msvc2017/lib/cmake/Qt5Core/Qt5CoreMacros.cmake:281 (_QT5_PARSE_QRC_FILE)
  client/CMakeLists.txt:14 (qt5_add_resources)

-- Configuring incomplete, errors occurred!
See also "F:/digidoc/DigiDoc4-Build/x86/CMakeFiles/CMakeOutput.log".

The same issue doesn't occur when using QT 5.12.6 . 
When I use QT 5.12.6, the output is entirely different and I can successfully compile DigiDoc4:
F:\digidoc\DigiDoc4-Build\x86>cmake -G"NMake Makefiles" "-DCMAKE_BUILD_TYPE=Release" -DQt5_DIR="F:\Qt\5.12.6\msvc2017\lib\cmake\Qt5" -DLIBDIGIDOCPP_LIBRARY="C:\LIBDIGIDOCPP\X86\DIGIDOCPP.LIB" -DLIBDIGIDOCPP_INCLUDE_DIR="C:\LIBDIGIDOCPP\INCLUDE" F:\digidoc\DigiDoc4-Client
-- The C compiler identification is MSVC 19.25.28611.0
-- The CXX compiler identification is MSVC 19.25.28611.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx86/x86/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx86/x86/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args`
  (PKCS11_Module) does not match the name of the calling package (PKCS11).
  This can lead to problems in calling code that expects `find_package`
  result variables (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindPKCS11.cmake:22 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:18 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PKCS11_Module: opensc-pkcs11.dll
-- Found LibDigiDocpp: C:/libdigidocpp/x86/digidocpp.lib (Required is at least version "3.14.3")
-- Found LDAP: C:/Program Files (x86)/Windows Kits/10/Lib/10.0.18362.0/um/x86/Wldap32.Lib
-- Found OpenSSL: optimized;C:/Program Files (x86)/OpenSSL-Win32/lib/VC/libcrypto32MD.lib;debug;C:/Program Files (x86)/OpenSSL-Win32/lib/VC/libcrypto32MDd.lib (found version "1.1.1d")
-- Configuring done
-- Generating done
-- Build files have been written to: F:/digidoc/DigiDoc4-Build/x86

Even when I later build the installer using WIX and bundle QT 5.12.7 instead of QT 5.12.6, the compiled DigiDoc4 binary works fine on Win7 x64 and Win10 1909 x64 virtual machines I test compiled binaries on. Obviously this is not an ideal situation and one should not mix up different versions during compiling and deployment scenarios.  Maybe there is a modification that has to be done to successfully link QT 5.12.6 libraries? Am I doing something incorrectly.

Thanks in advance for any feedback & advice!
Karl80038

**Comment by metsma** [comment]
Seems like Qt broke something in 5.12.7.
Tested with 5.12.5 and works fine

**Comment by karl80038** [comment]
It seems that something was fixed in QT 5.12.8 that previously caused the issue.
Now the configuration phase completes successfully and I can start building the binary:
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.5.4
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Windows\System32>f:

F:\>cd digidoc

F:\digidoc>cd digidoc4-build

F:\digidoc\DigiDoc4-Build>cd x64

F:\digidoc\DigiDoc4-Build\x64>set BUILD_NUMBER=2304

F:\digidoc\DigiDoc4-Build\x64>cmake -G"NMake Makefiles" "-DCMAKE_BUILD_TYPE=Release" -DQt5_DIR="F:\Qt\5.12.8\msvc2017_64\lib\cmake\Qt5" -DOPENSSL_ROOT_DIR="C:\Program Files\OpenSSL-Win64" -DLIBDIGIDOCPP_LIBRARY="C:\LIBDIGIDOCPP\x64\DIGIDOCPP.LIB" -DLIBDIGIDOCPP_INCLUDE_DIR="C:\LIBDIGIDOCPP\INCLUDE" F:\digidoc\DigiDoc4-Client
-- The C compiler identification is MSVC 19.25.28614.0
-- The CXX compiler identification is MSVC 19.25.28614.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args`
  (PKCS11_Module) does not match the name of the calling package (PKCS11).
  This can lead to problems in calling code that expects `find_package`
  result variables (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindPKCS11.cmake:22 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:18 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PKCS11_Module: opensc-pkcs11.dll
-- Found LibDigiDocpp: C:/libdigidocpp/x64/digidocpp.lib (Required is at least version "3.14.3")
-- Found LDAP: C:/Program Files (x86)/Windows Kits/10/Lib/10.0.18362.0/um/x64/Wldap32.Lib
-- Found OpenSSL: optimized;C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MD.lib;debug;C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MDd.lib (found version "1.1.1g")
-- Configuring done
-- Generating done
-- Build files have been written to: F:/digidoc/DigiDoc4-Build/x64

F:\digidoc\DigiDoc4-Build\x64>nmake

Microsoft (R) Program Maintenance Utility Version 14.25.28614.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Scanning dependencies of target qtsingleapplication_autogen
[  1%] Automatic MOC for target qtsingleapplication
[  1%] Built target qtsingleapplication_autogen
Scanning dependencies of target qtsingleapplication
[  2%] Building CXX object common/qtsingleapplication/CMakeFiles/qtsingleapplication.dir/qtsingleapplication_autogen/mocs_compilation.cpp.obj
mocs_compilation.cpp
[  2%] Building CXX object common/qtsingleapplication/CMakeFiles/qtsingleapplication.dir/src/qtlocalpeer.cpp.obj
qtlocalpeer.cpp
[  3%] Building CXX object common/qtsingleapplication/CMakeFiles/qtsingleapplication.dir/src/qtsingleapplication.cpp.obj
qtsingleapplication.cpp
[  4%] Linking CXX static library qtsingleapplication.lib
[  4%] Built target qtsingleapplication
Scanning dependencies of target qdigidoccommon_autogen
[  5%] Automatic MOC for target qdigidoccommon
[  5%] Built target qdigidoccommon_autogen
[  6%] Generating qtbase_et.qm
Updating 'F:/digidoc/DigiDoc4-Build/x64/common/qtbase_et.qm'...
    Generated 468 translation(s) (468 finished and 0 unfinished)
    Ignored 1005 untranslated source text(s)
[  7%] Generating qtbase_ru.qm
Updating 'F:/digidoc/DigiDoc4-Build/x64/common/qtbase_ru.qm'...
    Generated 1469 translation(s) (1469 finished and 0 unfinished)
    Ignored 4 untranslated source text(s)
[  7%] Generating common_en.qm
Updating 'F:/digidoc/DigiDoc4-Build/x64/common/common_en.qm'...
    Generated 11 translation(s) (11 finished and 0 unfinished)
[  8%] Generating common_et.qm
Updating 'F:/digidoc/DigiDoc4-Build/x64/common/common_et.qm'...
    Generated 11 translation(s) (11 finished and 0 unfinished)
[  9%] Generating common_ru.qm
Updating 'F:/digidoc/DigiDoc4-Build/x64/common/common_ru.qm'...
    Generated 11 translation(s) (11 finished and 0 unfinished)
[  9%] Generating qrc_common_tr.cpp
[ 10%] Generating qrc_config.cpp
Scanning dependencies of target qdigidoccommon
[ 11%] Building CXX object common/CMakeFiles/qdigidoccommon.dir/qdigidoccommon_autogen/mocs_compilation.cpp.obj
mocs_compilation.cpp
[ 11%] Building CXX object common/CMakeFiles/qdigidoccommon.dir/qrc_common_tr.cpp.obj
qrc_common_tr.cpp
[ 12%] Building CXX object common/CMakeFiles/qdigidoccommon.dir/Common.cpp.obj
Common.cpp
F:\digidoc\DigiDoc4-Client\common\Common.cpp(111): warning C4996: 'GetVersionExW': was declared deprecated
[ 13%] Building CXX object common/CMakeFiles/qdigidoccommon.dir/DateTime.cpp.obj
DateTime.cpp
[ 14%] Building CXX object common/CMakeFiles/qdigidoccommon.dir/IKValidator.cpp.obj
IKValidator.cpp
[ 14%] Building CXX object common/CMakeFiles/qdigidoccommon.dir/QPCSC.cpp.obj
QPCSC.cpp
[ 15%] Building CXX object common/CMakeFiles/qdigidoccommon.dir/qrc_config.cpp.obj
qrc_config.cpp
[ 16%] Building CXX object common/CMakeFiles/qdigidoccommon.dir/Configuration.cpp.obj
Configuration.cpp
[ 16%] Linking CXX static library qdigidoccommon.lib
[ 16%] Built target qdigidoccommon
Scanning dependencies of target TSLDownload_autogen
[ 16%] Automatic MOC for target TSLDownload
[ 16%] Built target TSLDownload_autogen
Scanning dependencies of target TSLDownload
[ 16%] Building CXX object client/CMakeFiles/TSLDownload.dir/TSLDownload_autogen/mocs_compilation.cpp.obj
mocs_compilation.cpp
[ 17%] Building CXX object client/CMakeFiles/TSLDownload.dir/TSLDownload.cpp.obj
TSLDownload.cpp
[ 18%] Linking CXX executable TSLDownload.exe
[ 18%] Built target TSLDownload
Scanning dependencies of target qdigidoc4_autogen
[ 19%] Automatic MOC for target qdigidoc4
[ 19%] Built target qdigidoc4_autogen
[ 20%] Generating en.qm
Updating 'F:/digidoc/DigiDoc4-Build/x64/client/en.qm'...
    Generated 774 translation(s) (774 finished and 0 unfinished)
[ 21%] Generating et.qm
Updating 'F:/digidoc/DigiDoc4-Build/x64/client/et.qm'...
    Generated 773 translation(s) (773 finished and 0 unfinished)
    Ignored 1 untranslated source text(s)
[ 21%] Generating ru.qm
Updating 'F:/digidoc/DigiDoc4-Build/x64/client/ru.qm'...
    Generated 773 translation(s) (773 finished and 0 unfinished)
    Ignored 1 untranslated source text(s)
[ 22%] Generating qrc_images.cpp
[ 23%] Generating qrc_fonts.cpp
[ 23%] Generating qrc_tr.cpp
[ 23%] Generating TSL.qrc
[ 24%] Generating qrc_TSL.cpp
[ 25%] Generating ui_MainWindow.h
[ 26%] Generating ui_AddRecipients.h
[ 26%] Generating ui_CertificateDetails.h
[ 27%] Generating ui_CertificateHistory.h
[ 28%] Generating ui_FirstRun.h
[ 28%] Generating ui_KeyDialog.h
[ 29%] Generating ui_MobileDialog.h
[ 30%] Generating ui_MobileProgress.h
[ 30%] Generating ui_PinPopup.h
[ 31%] Generating ui_PinUnblock.h
[ 32%] Generating ui_RoleAddressDialog.h
[ 33%] Generating ui_SettingsDialog.h
[ 33%] Generating ui_SignatureDialog.h
[ 34%] Generating ui_SmartIDDialog.h
[ 35%] Generating ui_WaitDialog.h
[ 35%] Generating ui_WarningDialog.h
[ 36%] Generating ui_Accordion.h
[ 37%] Generating ui_AccordionTitle.h
[ 37%] Generating ui_AddressItem.h
[ 38%] Generating ui_CardWidget.h
[ 39%] Generating ui_ContainerPage.h
[ 40%] Generating ui_FileItem.h
[ 40%] Generating ui_InfoStack.h
[ 41%] Generating ui_ItemList.h
[ 42%] Generating ui_MainAction.h
[ 42%] Generating ui_NoCardInfo.h
[ 43%] Generating ui_OtherData.h
[ 44%] Generating ui_PageIcon.h
[ 44%] Generating ui_SignatureItem.h
[ 45%] Generating ui_VerifyCert.h
[ 46%] Generating ui_WarningItem.h
[ 47%] Generating ui_WarningRibbon.h
Scanning dependencies of target qdigidoc4
[ 48%] Building CXX object client/CMakeFiles/qdigidoc4.dir/qdigidoc4_autogen/mocs_compilation.cpp.obj
mocs_compilation.cpp
[ 49%] Building RC object client/CMakeFiles/qdigidoc4.dir/qdigidoc4.rc.res
Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
Copyright (C) Microsoft Corporation.  All rights reserved.

[ 49%] Building CXX object client/CMakeFiles/qdigidoc4.dir/qrc_images.cpp.obj
qrc_images.cpp
[ 50%] Building CXX object client/CMakeFiles/qdigidoc4.dir/qrc_fonts.cpp.obj
qrc_fonts.cpp
[ 51%] Building CXX object client/CMakeFiles/qdigidoc4.dir/qrc_tr.cpp.obj
qrc_tr.cpp
[ 51%] Building CXX object client/CMakeFiles/qdigidoc4.dir/qrc_TSL.cpp.obj
qrc_TSL.cpp
[ 52%] Building CXX object client/CMakeFiles/qdigidoc4.dir/main.cpp.obj
main.cpp
[ 53%] Building CXX object client/CMakeFiles/qdigidoc4.dir/Application.cpp.obj
Application.cpp
F:\digidoc\DigiDoc4-Client\client\Application.cpp(408): warning C4150: deletion of pointer to incomplete type 'MacMenuBar'; no destructor called
F:\digidoc\DigiDoc4-Client\client\Application.cpp(65): note: see declaration of 'MacMenuBar'
[ 54%] Building CXX object client/CMakeFiles/qdigidoc4.dir/CheckConnection.cpp.obj
CheckConnection.cpp
[ 54%] Building CXX object client/CMakeFiles/qdigidoc4.dir/DigiDoc.cpp.obj
DigiDoc.cpp
[ 55%] Building CXX object client/CMakeFiles/qdigidoc4.dir/Diagnostics.cpp.obj
Diagnostics.cpp
[ 56%] Building CXX object client/CMakeFiles/qdigidoc4.dir/DiagnosticsTask.cpp.obj
DiagnosticsTask.cpp
[ 56%] Building CXX object client/CMakeFiles/qdigidoc4.dir/DocumentModel.cpp.obj
DocumentModel.cpp
[ 57%] Building CXX object client/CMakeFiles/qdigidoc4.dir/MainWindow.cpp.obj
MainWindow.cpp
[ 58%] Building CXX object client/CMakeFiles/qdigidoc4.dir/MainWindow_MyEID.cpp.obj
MainWindow_MyEID.cpp
[ 58%] Building CXX object client/CMakeFiles/qdigidoc4.dir/QCardLock.cpp.obj
QCardLock.cpp
[ 59%] Building CXX object client/CMakeFiles/qdigidoc4.dir/QPKCS11.cpp.obj
QPKCS11.cpp
[ 60%] Building CXX object client/CMakeFiles/qdigidoc4.dir/QSigner.cpp.obj
QSigner.cpp
[ 61%] Building CXX object client/CMakeFiles/qdigidoc4.dir/QSmartCard.cpp.obj
QSmartCard.cpp
[ 61%] Building CXX object client/CMakeFiles/qdigidoc4.dir/sslConnect.cpp.obj
sslConnect.cpp
[ 62%] Building CXX object client/CMakeFiles/qdigidoc4.dir/Styles.cpp.obj
Styles.cpp
[ 63%] Building CXX object client/CMakeFiles/qdigidoc4.dir/XmlReader.cpp.obj
XmlReader.cpp
[ 63%] Building CXX object client/CMakeFiles/qdigidoc4.dir/PrintSheet.cpp.obj
PrintSheet.cpp
[ 64%] Building CXX object client/CMakeFiles/qdigidoc4.dir/SslCertificate.cpp.obj
SslCertificate.cpp
[ 65%] Building CXX object client/CMakeFiles/qdigidoc4.dir/TokenData.cpp.obj
TokenData.cpp
[ 65%] Building CXX object client/CMakeFiles/qdigidoc4.dir/crypto/CryptoDoc.cpp.obj
CryptoDoc.cpp
[ 66%] Building CXX object client/CMakeFiles/qdigidoc4.dir/crypto/LdapSearch.cpp.obj
LdapSearch.cpp
[ 67%] Building CXX object client/CMakeFiles/qdigidoc4.dir/dialogs/AccessCert.cpp.obj
AccessCert.cpp
[ 68%] Building CXX object client/CMakeFiles/qdigidoc4.dir/dialogs/AddRecipients.cpp.obj
AddRecipients.cpp
[ 68%] Building CXX object client/CMakeFiles/qdigidoc4.dir/dialogs/CertificateDetails.cpp.obj
CertificateDetails.cpp
[ 69%] Building CXX object client/CMakeFiles/qdigidoc4.dir/dialogs/CertificateHistory.cpp.obj
CertificateHistory.cpp
[ 70%] Building CXX object client/CMakeFiles/qdigidoc4.dir/dialogs/FileDialog.cpp.obj
FileDialog.cpp
[ 70%] Building CXX object client/CMakeFiles/qdigidoc4.dir/dialogs/FirstRun.cpp.obj
FirstRun.cpp
[ 71%] Building CXX object client/CMakeFiles/qdigidoc4.dir/dialogs/KeyDialog.cpp.obj
KeyDialog.cpp
[ 72%] Building CXX object client/CMakeFiles/qdigidoc4.dir/dialogs/MobileDialog.cpp.obj
MobileDialog.cpp
[ 72%] Building CXX object client/CMakeFiles/qdigidoc4.dir/dialogs/MobileProgress.cpp.obj
MobileProgress.cpp
[ 73%] Building CXX object client/CMakeFiles/qdigidoc4.dir/dialogs/PinPopup.cpp.obj
PinPopup.cpp
[ 74%] Building CXX object client/CMakeFiles/qdigidoc4.dir/dialogs/PinUnblock.cpp.obj
PinUnblock.cpp
[ 75%] Building CXX object client/CMakeFiles/qdigidoc4.dir/dialogs/RoleAddressDialog.cpp.obj
RoleAddressDialog.cpp
[ 75%] Building CXX object client/CMakeFiles/qdigidoc4.dir/dialogs/SettingsDialog.cpp.obj
SettingsDialog.cpp
[ 76%] Building CXX object client/CMakeFiles/qdigidoc4.dir/dialogs/SmartIDDialog.cpp.obj
SmartIDDialog.cpp
[ 77%] Building CXX object client/CMakeFiles/qdigidoc4.dir/dialogs/SmartIDProgress.cpp.obj
SmartIDProgress.cpp
[ 77%] Building CXX object client/CMakeFiles/qdigidoc4.dir/dialogs/SignatureDialog.cpp.obj
SignatureDialog.cpp
[ 78%] Building CXX object client/CMakeFiles/qdigidoc4.dir/dialogs/WaitDialog.cpp.obj
WaitDialog.cpp
[ 79%] Building CXX object client/CMakeFiles/qdigidoc4.dir/dialogs/WarningDialog.cpp.obj
WarningDialog.cpp
[ 79%] Building CXX object client/CMakeFiles/qdigidoc4.dir/effects/ButtonHoverFilter.cpp.obj
ButtonHoverFilter.cpp
[ 80%] Building CXX object client/CMakeFiles/qdigidoc4.dir/effects/FadeInNotification.cpp.obj
FadeInNotification.cpp
[ 81%] Building CXX object client/CMakeFiles/qdigidoc4.dir/widgets/Accordion.cpp.obj
Accordion.cpp
[ 82%] Building CXX object client/CMakeFiles/qdigidoc4.dir/widgets/AccordionTitle.cpp.obj
AccordionTitle.cpp
[ 82%] Building CXX object client/CMakeFiles/qdigidoc4.dir/widgets/AddressItem.cpp.obj
AddressItem.cpp
[ 83%] Building CXX object client/CMakeFiles/qdigidoc4.dir/widgets/CardWidget.cpp.obj
CardWidget.cpp
[ 84%] Building CXX object client/CMakeFiles/qdigidoc4.dir/widgets/CardPopup.cpp.obj
CardPopup.cpp
[ 84%] Building CXX object client/CMakeFiles/qdigidoc4.dir/widgets/ContainerPage.cpp.obj
ContainerPage.cpp
[ 85%] Building CXX object client/CMakeFiles/qdigidoc4.dir/widgets/DropdownButton.cpp.obj
DropdownButton.cpp
[ 86%] Building CXX object client/CMakeFiles/qdigidoc4.dir/widgets/FileItem.cpp.obj
FileItem.cpp
[ 86%] Building CXX object client/CMakeFiles/qdigidoc4.dir/widgets/FileList.cpp.obj
FileList.cpp
[ 87%] Building CXX object client/CMakeFiles/qdigidoc4.dir/widgets/Item.cpp.obj
Item.cpp
[ 88%] Building CXX object client/CMakeFiles/qdigidoc4.dir/widgets/ItemList.cpp.obj
ItemList.cpp
F:\digidoc\DigiDoc4-Client\client\widgets\ItemList.cpp(129): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
[ 89%] Building CXX object client/CMakeFiles/qdigidoc4.dir/widgets/InfoStack.cpp.obj
InfoStack.cpp
[ 89%] Building CXX object client/CMakeFiles/qdigidoc4.dir/widgets/LabelButton.cpp.obj
LabelButton.cpp
[ 90%] Building CXX object client/CMakeFiles/qdigidoc4.dir/widgets/MainAction.cpp.obj
MainAction.cpp
[ 91%] Building CXX object client/CMakeFiles/qdigidoc4.dir/widgets/NoCardInfo.cpp.obj
NoCardInfo.cpp
[ 91%] Building CXX object client/CMakeFiles/qdigidoc4.dir/widgets/OtherData.cpp.obj
OtherData.cpp
[ 92%] Building CXX object client/CMakeFiles/qdigidoc4.dir/widgets/PageIcon.cpp.obj
PageIcon.cpp
[ 93%] Building CXX object client/CMakeFiles/qdigidoc4.dir/widgets/SignatureItem.cpp.obj
SignatureItem.cpp
[ 93%] Building CXX object client/CMakeFiles/qdigidoc4.dir/widgets/StyledWidget.cpp.obj
StyledWidget.cpp
F:\digidoc\DigiDoc4-Client\client\widgets\StyledWidget.cpp(34): warning C4138: '*/' found outside of comment
[ 94%] Building CXX object client/CMakeFiles/qdigidoc4.dir/widgets/VerifyCert.cpp.obj
VerifyCert.cpp
[ 95%] Building CXX object client/CMakeFiles/qdigidoc4.dir/widgets/WarningItem.cpp.obj
WarningItem.cpp
[ 96%] Building CXX object client/CMakeFiles/qdigidoc4.dir/widgets/WarningList.cpp.obj
WarningList.cpp
[ 96%] Building CXX object client/CMakeFiles/qdigidoc4.dir/widgets/WarningRibbon.cpp.obj
WarningRibbon.cpp
[ 97%] Building CXX object client/CMakeFiles/qdigidoc4.dir/QCSP.cpp.obj
QCSP.cpp
[ 98%] Building CXX object client/CMakeFiles/qdigidoc4.dir/QCNG.cpp.obj
QCNG.cpp
[ 98%] Building CXX object client/CMakeFiles/qdigidoc4.dir/QWin.cpp.obj
QWin.cpp
[ 99%] Building CXX object client/CMakeFiles/qdigidoc4.dir/CertStore.cpp.obj
CertStore.cpp
[100%] Building CXX object client/CMakeFiles/qdigidoc4.dir/Diagnostics_win.cpp.obj
Diagnostics_win.cpp
[100%] Linking CXX executable qdigidoc4.exe
[100%] Built target qdigidoc4

F:\digidoc\DigiDoc4-Build\x64>

The compiled binary also later runs successfully on my VM, as evidenced by the following image
![QT5128Successful](https://user-images.githubusercontent.com/50953098/80110119-0178e200-8587-11ea-84ab-0ba95c3b34f9.PNG)

It's interesting what change broke the compatibility QT 5.12.7, that the QT 5.12.8 fixed.

I know the upcoming question is out of scope from this topic, but how do you enable the use of test parameters, so one could for example, test Mobiil-ID (Mobile ID) using one of the test numbers.
Thanks in advance.

**Comment by kristelmerilain** [comment]
Qt version was updated in #751
