### ISSUE TITLE
TSL EE Signature is signed with untrusted certificate

### ISSUE THREAD

**Issue by jimmytheneutrino** [open-eid/DigiDoc4-Client#716]
Recently qdigidoc on my system does not trust (at least some) Estonian certificates. I cannot sign locally nor really check the validity of the container.

When running `strace -e trace=file qdigidoc4` (after cleaning all the configuration files from ~) I eventually get
```
ERROR [TSL.cpp:250] - TSL EE.xml status: TSL EE Signature is signed with untrusted certificate
DEBUG [Connect.cpp:48] - Connecting to URL: https://sr.riik.ee/tsl/estonian-tsl.xml
DEBUG [Connect.cpp:70] - Connecting to Host: sr.riik.ee:443 timeout: 10
DEBUG [TSL.cpp:507] - TSL EE Signature is signed with untrusted certificate
ERROR [TSL.cpp:285] - TSL EE.xml signature is invalid
```

It seems that that the xml is signed by the certificate (Estonian Trusted List Scheme Operator, issued at 19.01.2019) that qdigidoc (on my system) does not trust. Do I do something wrong or is it maybe a common problem (because of some changes in certificates)?

I am running Archlinux but the package there seems vanilla, taken from https://installer.id.ee/media/ubuntu/pool/main/q/qdigidoc4/qdigidoc4_4.2.4.71.orig.tar.xz as is.

**Comment by metsma** [comment]
Seems duplicate https://github.com/open-eid/libdigidocpp/issues/341
