### ISSUE TITLE
Are there any plans to support other eIDAS cards?

### ISSUE THREAD

**Issue by bertvandepoel** [open-eid/DigiDoc4-Client#872]
As a Belgian citizen, I'm very impressed to find the marvellous work the RIA has been doing on their open-eid ecosystem. After successfully trying out the hwcrypto demo (https://hwcrypto.github.io/demo/) with the open-eid software, I was hoping to also give DigiDoc a try. Sadly, while on the web I can easily sign using my Belgian eID, it's not recognised inside DigiDoc. I was wondering if there are any plans to support other PKCS11 devices or eIDAS cards.

I haven't read through all of the code, but I would think the infrastructure to support other cards is already largely there, since open-eid seems to already correctly detect my card and support signing using hwcrypto. I think it would be very much appreciated across the EU if DigiDoc would support generic eIDAS cards.

**Comment by metsma** [comment]
I think Windows should work out of the box. macOS&Linux need some minor help.
https://github.com/open-eid/DigiDoc4-Client/blob/master/client/QPKCS11.cpp#L347-L377

**Comment by bertvandepoel** [comment]
I see, I'm currently on Linux and wasn't aware there was a difference between platforms. Do you think this might be something that can land on Linux (and maybe also Mac) in the future?

**Comment by metsma** [comment]
https://github.com/open-eid/chrome-token-signing/blob/master/host-shared/PKCS11Path.cpp#L114
https://github.com/open-eid/chrome-token-signing/blob/master/host-shared/PKCS11Path.cpp#L132
https://github.com/open-eid/chrome-token-signing/blob/master/host-shared/PKCS11Path.cpp#L155
I think these are missing pieces

**Comment by bertvandepoel** [comment]
It seems indeed that the beid .so file is just missing under Linux conditions. Would it just be fixed by adding those, or is there more complexity?

**Comment by metsma** [comment]
I think this should do

**Comment by bertvandepoel** [comment]
I've added two lines in the hopes of writing a pull request. Now after adding loading information for beid on macOS (which I can't test but presume works) and Linux. DigiDoc4 correctly detected my eID and displayed my name and citizen number. However, something seems to go wrong when I try to sign a document:
```
ASiC_E.cpp:350 Failed to sign container.
SignatureXAdES_LT.cpp:228 Could not find certificate issuer 'serialNumber=201634,CN=Citizen CA,C=BE' in certificate store.
```
I initially thought that perhaps the Belgian TSL wasn't loaded correctly, however looking at CLI output I can see it's fine:
```
2020-12-08T10:04:43Z W [TSL.cpp:110] - Failed to parse TSL  /home/bert/.digidocpp/tsl//BE.xml: /home/bert/.digidocpp/tsl//BE.xml:1:2 error: invalid document structure
2020-12-08T10:04:43Z E [TSL.cpp:250] - TSL BE.xml status: Failed to parse XML
2020-12-08T10:04:43Z D [Connect.cpp:50] - Connecting to URL: https://tsl.belgium.be/tsl-be.xml
2020-12-08T10:04:43Z D [Connect.cpp:72] - Connecting to Host: tsl.belgium.be:443 timeout: 10
2020-12-08T10:04:43Z D [Connect.cpp:50] - Connecting to URL: https://sr.riik.ee/tsl/estonian-tsl.xml
2020-12-08T10:04:43Z D [Connect.cpp:72] - Connecting to Host: sr.riik.ee:443 timeout: 10
2020-12-08T10:04:43Z D [TSL.cpp:573] - Remote ETag: "4820b-5b5a01b1f8a80-gzip"
2020-12-08T10:04:43Z D [TSL.cpp:579] - Cached ETag: "4820b-5b5a01b1f8a80-gzip"
2020-12-08T10:04:43Z D [TSL.cpp:248] - TSL EE.xml (52) signature is valid
2020-12-08T10:04:43Z D [TSL.cpp:282] - TSL BE.xml (49) signature is valid
2020-12-08T10:04:43Z I [X509CertStore.cpp:84] - Loaded 100 certificates into TSL certificate store.
```
Now based on the error, I think the presumption may have been that the eID certificates are signed directly by a CA in the TSL. However, in the case of the Belgian eID, the CA signs an Intermediate Citizen CA which is then used to sign the actual certificates on the eID. These intermediates are generated quite often, I think monthly nowadays: http://repository.eid.belgium.be/certificates.php?cert=Citizen&lang=en

Is it possible that DigiDoc4 presumes the eID certificates are signed directly by the CA mentioned in the TSL?

**Comment by metsma** [comment]
Intresting. Is the Intermediate certificate also available on the card?
Or do we need fetch them from online somewhere?
I don't see that they are published in the TSL
https://webgate.ec.europa.eu/tl-browser/#/tl/BE/0

**Comment by bertvandepoel** [comment]
Oh right, I forgot to mention that. The card contains the full trust chain, so the Belgian Root CA (number 4 in my case) is included on the card (and also part of the TSL), as well as the Citizen CA that applies to my card and then my personal auth and sign certificates. It should be possible to fetch the intermediate certificate from the card. I'm not sure if any infrastructure for that is present in DigiDoc already?

**Comment by metsma** [comment]
This is something we need implement on the libdigidocpp library

**Comment by bertvandepoel** [comment]
Is it OK if I then file an issue on libdigidocpp and also submit the PR here already but reference the blocking issue on the side of libdigidocpp?

**Comment by metsma** [comment]
Yes

**Comment by kristelmerilain** [comment]
Closing due inactivity, reopen if needed.
