### ISSUE TITLE
Better UX for documentation of signature workflow

### ISSUE THREAD

**Issue by maltfield** [open-eid/DigiDoc4-Client#900]
Please document the correct procedure to sign files in the `qdigidoc4` GUI.

Currently, there *is* documentation for the `qdigidoc4` GUI on how to encrypt files here:

 * https://www.id.ee/en/article/encrypting-documents-with-ria-digidoc-app-4/

And there exists a page for how to sign files using `qdigidoc4` here, but it doesn't actually have any instructions on how to do it

 * https://www.id.ee/en/rubriik/signing/

Please update the above page to actually include instructions on how to sign documents using the `qdigidoc4` GUI application.

**Comment by maltfield** [comment]
The article just looks like a stub, but I found that if you scroll down to what looks like "related articles" you'll see a link to `You wish to add a digital signature using a computer`

 * https://www.id.ee/en/article/you-wish-to-add-a-digital-signature-using-a-computer-2/

**Comment by maltfield** [comment]
I'm changing this ticket to a UX feature request.

Please update the following page:

 * https://www.id.ee/en/rubriik/signing/

Has the following text

> A digital signature is an electronic signature that has the same legal validity as a handwritten signature. Digital signing is very simple. You will only need a digital document (e.g. an ID-card, digi-ID, mobile-ID or Smart-ID) and a signing solution (e.g. ID software or RIA DigiDoc mobile app).

Replaced by the following text

> A digital signature is an electronic signature that has the same legal validity as a handwritten signature. Digital signing is very simple. You will only need a digital document (e.g. an ID-card, digi-ID, mobile-ID or Smart-ID) and a signing solution (e.g. ID software or RIA DigiDoc mobile app).
> 
> For instructions on how to sign a file on [mobile using the RIA DigiDoc app, click here](https://www.id.ee/en/article/digital-signing-in-ria-digidoc-mobile-application-3/)
>
> For instructions on how to [sign a file on a desktop using DigiDoc4, click here](https://www.id.ee/en/article/you-wish-to-add-a-digital-signature-using-a-computer-2/)

**Comment by Counter178** [comment]
The message has been passed to the webmaster for possible future updates. Will recommend sending these kinds of issues directly to the mainstream https://www.id.ee/en/article/notify-us-of-the-problem/ .
