### ISSUE TITLE
Document GUI workflow for signing *and* encrypting files

### ISSUE THREAD

**Issue by maltfield** [open-eid/DigiDoc4-Client#901]
Please document the correct procedure to sign and encrypt files in the `qdigidoc4` GUI.

Currently, there *is* documentation for the `qdigidoc4` GUI on how to encrypt files here:

 * https://www.id.ee/en/article/encrypting-documents-with-ria-digidoc-app-4/

And there exists (a stub -- see https://github.com/open-eid/DigiDoc4-Client/issues/900) a page for how to sign files using `qdigidoc4` here:

 * https://www.id.ee/en/rubriik/signing/

...but nowhere could I find instructions on how to both sign and encrypt a file. Indeed, in my first experience with corresponding with Estonian citizens, they sent me encrypted but unsigned messages. This is a huge issue.

I was able to encrypt and sign a file using `qdigidoc4` myself by both:

1. first signing the file (to create `file.asice`) then encrypting the signed file (to create `file.cdoc`) and
1. first encrypting the file (to create `file.cdoc`) then signing the encrypted file (to create `file.asice`)

In theory I guess both work, but one (`file.asice`) is a binary file and the other (`file.cdoc`) appears to be an xml file. I imagine there is a best-practice for what the order should be. And I imagine there's an easier way to just encrypt & sign at the same time?

Please document the recommended procedure to both sign *and* encrypt files using the `qdigidoc4` GUI.

**Comment by Counter178** [comment]
Related to https://github.com/open-eid/DigiDoc4-Client/issues/900 and notified.
