### ISSUE TITLE
Document CLI usage

### ISSUE THREAD

**Issue by maltfield** [open-eid/DigiDoc4-Client#902]
Please create documentation for how to use the `digidoc-tool` command-line tool.

This repo and the https://id.ee website contains great documentation on how to install `open-eid`, but it's seriously lacking documentation on how to use its tools after installation. For example, I could find no documentation (other than the `man digidoc-tool` man page, which doesn't even list how to encrypt files) on how to encrypt or sign a file with `digidoc-tool` anywhere on your website or this repo.

Please document how to to do the following with the `digidoc-tool

1. encrypt files 
2. sign files
3. encrypt and sign files

**Comment by Counter178** [comment]
The documentation reference is added to https://github.com/open-eid/DigiDoc4-Client/wiki/DeveloperTips , where it redirects to  http://open-eid.github.io/libdigidocpp/manual.html#utility .

**Comment by maltfield** [comment]
Thank you, but I think this is still an issue.

Can you please update `README.md` and the following website to link to this? I never would have looked in the wiki page on developer tips for usage instructions:

 * https://github.com/open-eid/DigiDoc4-Client/blob/master/README.md
 * https://open-eid.github.io/

**Comment by maltfield** [comment]
Sorry, I think you misunderstood this issue. I don't see any usage documentation on the page you provided that says how to encrypt and sign a file

 * http://open-eid.github.io/libdigidocpp/manual.html#utility

There is some information about signing, but I see nothing about how to encrypt a file with the `digidoc-tool` cli command..

**Comment by metsma** [comment]
There is no CLI for encryption in DigiDoc4 or libdigidocpp. You can use digidoc4j java library

**Comment by Counter178** [comment]
Like previous comment suggested, recommend using DD4j  https://github.com/open-eid/digidoc4j/wiki
