### ISSUE TITLE
"Ümbriku allkirjastamine ebaõnnestus"

### ISSUE THREAD

**Issue by piiskop** [open-eid/DigiDoc4-Client#919]
Laadisin faili tarkvarasse ja vajutasin _ALLKIRJASTA ID-KAARDIGA_. Küsis PIN'i, mille sisestasin ja vajutasin _OK_. Nooled keerlesid ja seejärel kuvati:

> Ümbriku allkirjastamine ebaõnnestus

Vajutasin _Detailid_ ja seejärel kuvati:

> ASiC_E.cpp:347 Failed to sign container.
> SignatureXAdES_LT.cpp:217 Could not find certificate issuer 'CN=ESTEID-SK 2015,organizationIdentifier=NTREE-10747013,O=AS Sertifitseerimiskeskus,C=EE' in certificate store.

**Comment by Counter178** [comment]
The intermediate certificate is missing from the OS certificate store https://www.skidsolutions.eu/en/repository/certs/ .  
 Either policy or something hasn't been updated from OS side.

**Comment by metsma** [comment]
No libdigidocpp does not use OS certificate store. 
There is issue with libdigidocpp TSL loading, you can enable logging to debug the issue
http://open-eid.github.io/libdigidocpp/manual.html#logging-settings

**Comment by kristelmerilain** [comment]
Closing due inactivity, reopen if needed.

**Comment by piiskop** [comment]
As of 20210408, this issue still isn't resolved. Why do you close it due inactivity instead of being active and solve the issue?

**Comment by kristelmerilain** [comment]
If this problem is still active then please enable logging and add logs to debug the issue http://open-eid.github.io/libdigidocpp/manual.html#logging-settings or contact the ID-helpline via id.ee https://www.id.ee/en/article/notify-us-of-the-problem/

**Comment by piiskop** [comment]
I read that recommendation already. I have no idea how to use the referenced `log.level`. I'm not a programmer but an end-user of this software. If that debugging means diagnostics then it's here:

> Keeleseaded: English/United States / C.UTF-8
> 
> Rakenduse versioon: 4.2.3.60 (64 bit)
> Operatsioonisüsteem: Ubuntu 20.10
> Protsessor: Intel(R) Core(TM) i5 CPU M 460 @ 2.53GHz
> Tuum: Linux 5.8.0-48-generic #54-Ubuntu SMP Fri Mar 19 14:25:20 UTC 2021 x86_64
> 
> Teegid:
> libdigidoc2 (3.10.5-1)
> libdigidocpp1 (3.14.1.1388-1904)
> qdigidoc-tera (1.2.0.253-1904)
> firefox-pkcs11-loader (3.13.3.1076-1904)
> chrome-token-signing (1:1.1.0.511-1904)
> openssl (1.1.1f-1ubuntu4.3)
> libpcsclite1 (1.9.0-1)
> opensc (0.20.0-4)
> QT (5.14.2)
> 
> Argumendid: qdigidoc4
> Teegi otsing: /usr/lib/x86_64-linux-gnu/qt5/plugins;/usr/bin
> URLs:
> CONFIG_URL: https://id.eesti.ee/config.json
> TSL_URL: https://ec.europa.eu/tools/lotl/eu-lotl.xml (250)
> TSA_URL: http://dd-at.ria.ee/tsa
> SIVA_URL: https://siva.eesti.ee/V3/validate
> 
> TSL signeerimise sertifikaadid:
> Patrick Kremer (Signature)
> GEORGIOS LAPPAS
> JEROEN ARNOLD L RATHE
> APOSTOLOS APLADAS
> CONSTANTIN-ADRIAN CROITORU
> European Commission
> European Commission
> 
> Konfiguratsiooni andmed:
> DATE: 20210331110015Z
> SERIAL: 122
> URL: https://id.eesti.ee/config.json
> VER: 1
> 
> Smart Card teenuse staatus: Töötab
> Kaardilugejad:
> ACS ACR 38U-CCID 00 00 max APDU size 65536
> Reader state: PRESENT, INUSE
> ATR cold - 3BFA1800008031FE45FE654944202F20504B4903
> ATR warm - 3BFE1800008031FE45803180664090A4162A00830F9000EF
> AID34: 6a82 (Not found)
> AID35: 9000 (OK)
> ID - 37804080345
> 
> 
> Veebibrauserid:
> firefox (87.0+build3-0ubuntu0.20.10.1)
> google-chrome-stable (89.0.4389.114-1)
> 
> USB info:
> Bus 002 Device 005: ID 0a5c:21b4 Broadcom Corp. BCM2070 Bluetooth 2.1 + EDR
> Bus 002 Device 004: ID 1131:1810 Integrated System Solution Corp. 
> Bus 002 Device 003: ID 1bcf:0005 Sunplus Innovation Technology Inc. Optical Mouse
> Bus 002 Device 002: ID 8087:0020 Intel Corp. Integrated Rate Matching Hub
> Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> Bus 001 Device 003: ID 05c8:0403 Cheng Uei Precision Industry Co., Ltd (Foxlink) Webcam
> Bus 001 Device 004: ID 072f:90cc Advanced Card Systems, Ltd ACR38 SmartCard Reader
> Bus 001 Device 002: ID 8087:0020 Intel Corp. Integrated Rate Matching Hub
> Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> 
> 
> Apleti versioon: 3.5.8

**Comment by kristelmerilain** [comment]
In order to be able to find a solution to your problem, please contact the ID-helpline via the web form on the id.ee website: https://www.id.ee/en/article/notify-us-of-the-problem/

**Comment by karl80038** [comment]
> I read that recommendation already. I have no idea how to use the referenced `log.level`. I'm not a programmer but an end-user of this software. If that debugging means diagnostics then it's here:
> 
> > Keeleseaded: English/United States / C.UTF-8
> > Rakenduse versioon: 4.2.3.60 (64 bit)
> > Operatsioonisüsteem: Ubuntu 20.10
> > Protsessor: Intel(R) Core(TM) i5 CPU M 460 @ 2.53GHz
> > Tuum: Linux 5.8.0-48-generic #54-Ubuntu SMP Fri Mar 19 14:25:20 UTC 2021 x86_64
> > Teegid:
> > libdigidoc2 (3.10.5-1)
> > libdigidocpp1 (3.14.1.1388-1904)
> > qdigidoc-tera (1.2.0.253-1904)
> > firefox-pkcs11-loader (3.13.3.1076-1904)
> > chrome-token-signing (1:1.1.0.511-1904)
> > openssl (1.1.1f-1ubuntu4.3)
> > libpcsclite1 (1.9.0-1)
> > opensc (0.20.0-4)
> > QT (5.14.2)
> > Argumendid: qdigidoc4
> > Teegi otsing: /usr/lib/x86_64-linux-gnu/qt5/plugins;/usr/bin
> > URLs:
> > CONFIG_URL: https://id.eesti.ee/config.json
> > TSL_URL: https://ec.europa.eu/tools/lotl/eu-lotl.xml (250)
> > TSA_URL: http://dd-at.ria.ee/tsa
> > SIVA_URL: https://siva.eesti.ee/V3/validate
> > TSL signeerimise sertifikaadid:
> > Patrick Kremer (Signature)
> > GEORGIOS LAPPAS
> > JEROEN ARNOLD L RATHE
> > APOSTOLOS APLADAS
> > CONSTANTIN-ADRIAN CROITORU
> > European Commission
> > European Commission
> > Konfiguratsiooni andmed:
> > DATE: 20210331110015Z
> > SERIAL: 122
> > URL: https://id.eesti.ee/config.json
> > VER: 1
> > Smart Card teenuse staatus: Töötab
> > Kaardilugejad:
> > ACS ACR 38U-CCID 00 00 max APDU size 65536
> > Reader state: PRESENT, INUSE
> > ATR cold - 3BFA1800008031FE45FE654944202F20504B4903
> > ATR warm - 3BFE1800008031FE45803180664090A4162A00830F9000EF
> > AID34: 6a82 (Not found)
> > AID35: 9000 (OK)
> > ID - 37804080345
> > Veebibrauserid:
> > firefox (87.0+build3-0ubuntu0.20.10.1)
> > google-chrome-stable (89.0.4389.114-1)
> > USB info:
> > Bus 002 Device 005: ID 0a5c:21b4 Broadcom Corp. BCM2070 Bluetooth 2.1 + EDR
> > Bus 002 Device 004: ID 1131:1810 Integrated System Solution Corp.
> > Bus 002 Device 003: ID 1bcf:0005 Sunplus Innovation Technology Inc. Optical Mouse
> > Bus 002 Device 002: ID 8087:0020 Intel Corp. Integrated Rate Matching Hub
> > Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> > Bus 001 Device 003: ID 05c8:0403 Cheng Uei Precision Industry Co., Ltd (Foxlink) Webcam
> > Bus 001 Device 004: ID 072f:90cc Advanced Card Systems, Ltd ACR38 SmartCard Reader
> > Bus 001 Device 002: ID 8087:0020 Intel Corp. Integrated Rate Matching Hub
> > Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> > Apleti versioon: 3.5.8
You are using the outdated version of the eID-software. The latest installation package can be obtained from https://www.id.ee/artikkel/paigalda-id-tarkvara/ . You should also be able to update to the latest version by running sudo apt-get update && sudo apt-get upgrade

**Comment by piiskop** [comment]
Why did you copy my post without commenting it?

@kristelmerilain I did it.

**Comment by kristelmerilain** [comment]
@karl80038 copied your post and added his comment at the end "You are using the outdated version of the eID-software. The latest installation package can be obtained from https://www.id.ee/artikkel/paigalda-id-tarkvara/ . You should also be able to update to the latest version by running sudo apt-get update && sudo apt-get upgrade". 
He is right you should update your ID-software because you have quite old version. Maybe this article helps: https://www.id.ee/en/article/ubuntu-id-software-installation-updating-and-removal/#software-update

**Comment by piiskop** [comment]
I see. @karl80038  wrote his comment as if it'd be mine. This is the reason why I didn't notice it.

@kristelmerilain, your suggested upgrade via _apt_ didn't fix the software. _apt_ didn't find any upgrade because the corresponding repository was turned off for upgrading the operating system from _disco_ to _focal_. I turned them all in:

```
peacecop@peacecop-HP-ProBook-4520s:/etc/apt/sources.list.d$ sudo emacs ria-repository.list
peacecop@peacecop-HP-ProBook-4520s:/etc/apt/sources.list.d$ sudo emacs ria-repository.list.distUpgrade 
peacecop@peacecop-HP-ProBook-4520s:/etc/apt/sources.list.d$ sudo emacs ria-repository.list.save
```
I changed _disco_ to _groovy_:
`deb https://installer.id.ee/media/ubuntu/ groovy main # disabled on upgrade to focal`

This time, _apt_ upgraded _id_ and signing using _DigiDoc4 Client_ went just fine.
