### ISSUE TITLE
Can not download capatible version from app store

### ISSUE THREAD

**Issue by yuessir** [open-eid/DigiDoc4-Client#968]
My macOS is `Sierra(10.12)` version, can not donload from the app store.

**Comment by karl80038** [comment]
MacOS 10.12 is unfortunately no longer supported. Newer releases of DigiDoc4 are compiled with QT 5.12, which itself no longer supports anything older than 10.13. It might be possible to compile the latest version with QT 5.9 and change the minimum targeted OS version, but even then the application might not run properly even if the project does compile successfully. The last version compatible with macOS 10.11 that might also run on 10.12 is 4.2.4, however using older releases is generally unadvised as they are unsupported and their proper operation as the time moves forward is not guaranteed. Older compiled releases might be available under the Releases section. I'd strongly recommend upgrading to at least macOS 10.14 (there are workarounds to install newer versions of macOS on unsupported systems, if the system officially doesn't support a newer version) or create a dual-boot system with Ubuntu Linux.

**Comment by yuessir** [comment]
Found sources form https://installer.id.ee/media/sources/

https://installer.id.ee/media/osx/Open-EID_20.12.0.1897.dmg
