### ISSUE TITLE
Make a flatpak release

### ISSUE THREAD

**Issue by ilyachch** [open-eid/DigiDoc4-Client#969]
For now, there is no way to install this software on Ubuntu 21.04 and it's derivatives, such as Pop! Os.
Flatpak is already almost a standard of publishing apps.
Such distribution method will allow to focus on updates, not preparing releases for new versions of OS's.
Also, it's possible to create own flatpak repo, if Flafhub is not trusted.

**Comment by kristelmerilain** [comment]
Thank you for the proposal.
We have added analysis of the ID-software packaging options (Snap, Flatpak, Appimage) in our roadmap to provide better support across Linux distributions (planned to begin at the end of this year).

**Comment by MysteriousNothing** [comment]
@ilyachch Some dude from Estonia already done this.https://github.com/oskarkook/qdigidoc-flatpak

Official development team needs  another year to ride on tax payers. Absolute clowns, can't even write basic tests.
DDC4 is broken cross distro, yikes!

**Comment by allanlaal** [comment]
this feature should also include autopublishing new stable releases to Flathub, so ppl would have autoupdates

can you do it for 4 billion €? :dagger: :laughing:

**Comment by metsma** [comment]
https://ludovicrousseau.blogspot.com/2022/02/fedora-flatpak-and-pcsc-lite.html

**Comment by pauljamesharper** [comment]
Debian 12 User. I just got my E-Residency. :) Flatpak would get my vote. But if you could manage flatpak/snap/appimage you would probably cover most Linux users.

**Comment by minosimo** [comment]
If I were to submit the digidoc client to Flathub, would RIA be opposed to this? I think it would be excellent to have the client more widely available across distributions. The application would be clearly labeled as "unofficial" in the description.

**Comment by metsma** [comment]
How do you resolve the fedora problem? Will you upload two different packages? How to instruct user to select correct package?

**Comment by minosimo** [comment]
The separate built is [no longer needed](https://github.com/minosimo/qdigidoc-flatpak/commit/9195dc02f4ea13f9b9f11a7115c0b10b5b45cb6b)

**Comment by minosimo** [comment]
qdigidoc4 has been accepted by FlatHub! For now I'm the maintainer but if RIA has any interest in maintenance, I will gladly transfer the repo: https://flathub.org/apps/ee.ria.qdigidoc4

**Comment by ilyachch** [comment]
That is really great news!
Thank you so much!

**Comment by metsma** [comment]
Under ubuntu ASiC containers do not have icons.
Does this support nautilus right click on file and sign command?
