### ISSUE TITLE
Latvian card incorrectly sets mechanism to CKM_RSA_PKCS when it should be CKM_SHA256_RSA_PKCS

### ISSUE THREAD

**Issue by eidins** [open-eid/DigiDoc4-Client#999]
https://github.com/open-eid/DigiDoc4-Client/blob/132de43aebe116a237d1dde643634af6afe49f37/client/QPKCS11.cpp#L395-L401

See https://github.com/OpenSC/OpenSC/pull/2428#issuecomment-962452011

**Comment by eidins** [comment]
Possibly Related https://github.com/open-eid/libdigidocpp/issues/442

**Comment by metsma** [comment]
No it is expected to be CKM_RSA_PKCS and it works with propertary driver. OpenSC needs to be fixed
